/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "./models";
import * as Mappers from "./models/mappers";
import * as operations from "./operations";
import { AuthorizationManagementClientContext } from "./authorizationManagementClientContext";


class AuthorizationManagementClient extends AuthorizationManagementClientContext {
  // Operation groups
  operations: operations.Operations;
  accessReviewScheduleDefinitions: operations.AccessReviewScheduleDefinitions;
  accessReviewInstances: operations.AccessReviewInstances;
  accessReviewInstance: operations.AccessReviewInstanceOperations;
  accessReviewInstanceDecisions: operations.AccessReviewInstanceDecisions;
  accessReviewDefaultSettings: operations.AccessReviewDefaultSettingsOperations;
  accessReviewScheduleDefinitionsAssignedForMyApproval: operations.AccessReviewScheduleDefinitionsAssignedForMyApproval;
  accessReviewInstancesAssignedForMyApproval: operations.AccessReviewInstancesAssignedForMyApproval;
  accessReviewInstanceMyDecisions: operations.AccessReviewInstanceMyDecisions;

  /**
   * Initializes a new instance of the AuthorizationManagementClient class.
   * @param credentials Credentials needed for the client to connect to Azure.
   * @param subscriptionId The ID of the target subscription.
   * @param [options] The parameter options
   */
  constructor(credentials: msRest.ServiceClientCredentials, subscriptionId: string, options?: Models.AuthorizationManagementClientOptions) {
    super(credentials, subscriptionId, options);
    this.operations = new operations.Operations(this);
    this.accessReviewScheduleDefinitions = new operations.AccessReviewScheduleDefinitions(this);
    this.accessReviewInstances = new operations.AccessReviewInstances(this);
    this.accessReviewInstance = new operations.AccessReviewInstanceOperations(this);
    this.accessReviewInstanceDecisions = new operations.AccessReviewInstanceDecisions(this);
    this.accessReviewDefaultSettings = new operations.AccessReviewDefaultSettingsOperations(this);
    this.accessReviewScheduleDefinitionsAssignedForMyApproval = new operations.AccessReviewScheduleDefinitionsAssignedForMyApproval(this);
    this.accessReviewInstancesAssignedForMyApproval = new operations.AccessReviewInstancesAssignedForMyApproval(this);
    this.accessReviewInstanceMyDecisions = new operations.AccessReviewInstanceMyDecisions(this);
  }
}

// Operation Specifications

export {
  AuthorizationManagementClient,
  AuthorizationManagementClientContext,
  Models as AuthorizationManagementModels,
  Mappers as AuthorizationManagementMappers
};
export * from "./operations";
