/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import {
  AccessReviewInstanceStopOptionalParams,
  AccessReviewInstanceResetDecisionsOptionalParams,
  AccessReviewInstanceApplyDecisionsOptionalParams,
  AccessReviewInstanceSendRemindersOptionalParams,
  AccessReviewInstanceAcceptRecommendationsOptionalParams
} from "../models";

/** Interface representing a AccessReviewInstanceOperations. */
export interface AccessReviewInstanceOperations {
  /**
   * An action to stop an access review instance.
   * @param subscriptionId The ID of the target subscription.
   * @param scheduleDefinitionId The id of the access review schedule definition.
   * @param id The id of the access review instance.
   * @param options The options parameters.
   */
  stop(
    subscriptionId: string,
    scheduleDefinitionId: string,
    id: string,
    options?: AccessReviewInstanceStopOptionalParams
  ): Promise<void>;
  /**
   * An action to reset all decisions for an access review instance.
   * @param subscriptionId The ID of the target subscription.
   * @param scheduleDefinitionId The id of the access review schedule definition.
   * @param id The id of the access review instance.
   * @param options The options parameters.
   */
  resetDecisions(
    subscriptionId: string,
    scheduleDefinitionId: string,
    id: string,
    options?: AccessReviewInstanceResetDecisionsOptionalParams
  ): Promise<void>;
  /**
   * An action to apply all decisions for an access review instance.
   * @param subscriptionId The ID of the target subscription.
   * @param scheduleDefinitionId The id of the access review schedule definition.
   * @param id The id of the access review instance.
   * @param options The options parameters.
   */
  applyDecisions(
    subscriptionId: string,
    scheduleDefinitionId: string,
    id: string,
    options?: AccessReviewInstanceApplyDecisionsOptionalParams
  ): Promise<void>;
  /**
   * An action to send reminders for an access review instance.
   * @param subscriptionId The ID of the target subscription.
   * @param scheduleDefinitionId The id of the access review schedule definition.
   * @param id The id of the access review instance.
   * @param options The options parameters.
   */
  sendReminders(
    subscriptionId: string,
    scheduleDefinitionId: string,
    id: string,
    options?: AccessReviewInstanceSendRemindersOptionalParams
  ): Promise<void>;
  /**
   * An action to accept recommendations for decision in an access review instance.
   * @param scheduleDefinitionId The id of the access review schedule definition.
   * @param id The id of the access review instance.
   * @param options The options parameters.
   */
  acceptRecommendations(
    scheduleDefinitionId: string,
    id: string,
    options?: AccessReviewInstanceAcceptRecommendationsOptionalParams
  ): Promise<void>;
}
