# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
            
trigger:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
    exclude:
      - feature/v4
  paths:
    include:
      - sdk/scan/arm-scan
      - sdk/scan/ci.mgmt.yml

pr:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
    exclude:
      - feature/v4
  paths:
    include:
      - sdk/scan/arm-scan
      - sdk/scan/ci.mgmt.yml

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: scan
    Artifacts:
      - name: azure-arm-scan
        safeName: azurearmscan
        