/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { PagedAsyncIterableIterator } from "@azure/core-paging";
import { GuestAgents } from "../operationsInterfaces";
import * as coreClient from "@azure/core-client";
import * as Mappers from "../models/mappers";
import * as Parameters from "../models/parameters";
import { AzureArcVMwareManagementServiceAPI } from "../azureArcVMwareManagementServiceAPI";
import { PollerLike, PollOperationState, LroEngine } from "@azure/core-lro";
import { LroImpl } from "../lroImpl";
import {
  GuestAgent,
  GuestAgentsListNextOptionalParams,
  GuestAgentsListOptionalParams,
  GuestAgentsCreateOptionalParams,
  GuestAgentsCreateResponse,
  GuestAgentsGetOptionalParams,
  GuestAgentsGetResponse,
  GuestAgentsDeleteOptionalParams,
  GuestAgentsListResponse,
  GuestAgentsListNextResponse
} from "../models";

/// <reference lib="esnext.asynciterable" />
/** Class containing GuestAgents operations. */
export class GuestAgentsImpl implements GuestAgents {
  private readonly client: AzureArcVMwareManagementServiceAPI;

  /**
   * Initialize a new instance of the class GuestAgents class.
   * @param client Reference to the service client
   */
  constructor(client: AzureArcVMwareManagementServiceAPI) {
    this.client = client;
  }

  /**
   * Returns the list of GuestAgent of the given vm.
   * @param resourceGroupName The Resource Group Name.
   * @param virtualMachineName Name of the vm.
   * @param options The options parameters.
   */
  public list(
    resourceGroupName: string,
    virtualMachineName: string,
    options?: GuestAgentsListOptionalParams
  ): PagedAsyncIterableIterator<GuestAgent> {
    const iter = this.listPagingAll(
      resourceGroupName,
      virtualMachineName,
      options
    );
    return {
      next() {
        return iter.next();
      },
      [Symbol.asyncIterator]() {
        return this;
      },
      byPage: () => {
        return this.listPagingPage(
          resourceGroupName,
          virtualMachineName,
          options
        );
      }
    };
  }

  private async *listPagingPage(
    resourceGroupName: string,
    virtualMachineName: string,
    options?: GuestAgentsListOptionalParams
  ): AsyncIterableIterator<GuestAgent[]> {
    let result = await this._list(
      resourceGroupName,
      virtualMachineName,
      options
    );
    yield result.value || [];
    let continuationToken = result.nextLink;
    while (continuationToken) {
      result = await this._listNext(
        resourceGroupName,
        virtualMachineName,
        continuationToken,
        options
      );
      continuationToken = result.nextLink;
      yield result.value || [];
    }
  }

  private async *listPagingAll(
    resourceGroupName: string,
    virtualMachineName: string,
    options?: GuestAgentsListOptionalParams
  ): AsyncIterableIterator<GuestAgent> {
    for await (const page of this.listPagingPage(
      resourceGroupName,
      virtualMachineName,
      options
    )) {
      yield* page;
    }
  }

  /**
   * Create Or Update GuestAgent.
   * @param resourceGroupName The Resource Group Name.
   * @param virtualMachineName Name of the vm.
   * @param name Name of the guestAgents.
   * @param options The options parameters.
   */
  async beginCreate(
    resourceGroupName: string,
    virtualMachineName: string,
    name: string,
    options?: GuestAgentsCreateOptionalParams
  ): Promise<
    PollerLike<
      PollOperationState<GuestAgentsCreateResponse>,
      GuestAgentsCreateResponse
    >
  > {
    const directSendOperation = async (
      args: coreClient.OperationArguments,
      spec: coreClient.OperationSpec
    ): Promise<GuestAgentsCreateResponse> => {
      return this.client.sendOperationRequest(args, spec);
    };
    const sendOperation = async (
      args: coreClient.OperationArguments,
      spec: coreClient.OperationSpec
    ) => {
      let currentRawResponse:
        | coreClient.FullOperationResponse
        | undefined = undefined;
      const providedCallback = args.options?.onResponse;
      const callback: coreClient.RawResponseCallback = (
        rawResponse: coreClient.FullOperationResponse,
        flatResponse: unknown
      ) => {
        currentRawResponse = rawResponse;
        providedCallback?.(rawResponse, flatResponse);
      };
      const updatedArgs = {
        ...args,
        options: {
          ...args.options,
          onResponse: callback
        }
      };
      const flatResponse = await directSendOperation(updatedArgs, spec);
      return {
        flatResponse,
        rawResponse: {
          statusCode: currentRawResponse!.status,
          body: currentRawResponse!.parsedBody,
          headers: currentRawResponse!.headers.toJSON()
        }
      };
    };

    const lro = new LroImpl(
      sendOperation,
      { resourceGroupName, virtualMachineName, name, options },
      createOperationSpec
    );
    const poller = new LroEngine(lro, {
      resumeFrom: options?.resumeFrom,
      intervalInMs: options?.updateIntervalInMs,
      lroResourceLocationConfig: "azure-async-operation"
    });
    await poller.poll();
    return poller;
  }

  /**
   * Create Or Update GuestAgent.
   * @param resourceGroupName The Resource Group Name.
   * @param virtualMachineName Name of the vm.
   * @param name Name of the guestAgents.
   * @param options The options parameters.
   */
  async beginCreateAndWait(
    resourceGroupName: string,
    virtualMachineName: string,
    name: string,
    options?: GuestAgentsCreateOptionalParams
  ): Promise<GuestAgentsCreateResponse> {
    const poller = await this.beginCreate(
      resourceGroupName,
      virtualMachineName,
      name,
      options
    );
    return poller.pollUntilDone();
  }

  /**
   * Implements GuestAgent GET method.
   * @param resourceGroupName The Resource Group Name.
   * @param virtualMachineName Name of the vm.
   * @param name Name of the GuestAgent.
   * @param options The options parameters.
   */
  get(
    resourceGroupName: string,
    virtualMachineName: string,
    name: string,
    options?: GuestAgentsGetOptionalParams
  ): Promise<GuestAgentsGetResponse> {
    return this.client.sendOperationRequest(
      { resourceGroupName, virtualMachineName, name, options },
      getOperationSpec
    );
  }

  /**
   * Implements GuestAgent DELETE method.
   * @param resourceGroupName The Resource Group Name.
   * @param virtualMachineName Name of the vm.
   * @param name Name of the GuestAgent.
   * @param options The options parameters.
   */
  async beginDelete(
    resourceGroupName: string,
    virtualMachineName: string,
    name: string,
    options?: GuestAgentsDeleteOptionalParams
  ): Promise<PollerLike<PollOperationState<void>, void>> {
    const directSendOperation = async (
      args: coreClient.OperationArguments,
      spec: coreClient.OperationSpec
    ): Promise<void> => {
      return this.client.sendOperationRequest(args, spec);
    };
    const sendOperation = async (
      args: coreClient.OperationArguments,
      spec: coreClient.OperationSpec
    ) => {
      let currentRawResponse:
        | coreClient.FullOperationResponse
        | undefined = undefined;
      const providedCallback = args.options?.onResponse;
      const callback: coreClient.RawResponseCallback = (
        rawResponse: coreClient.FullOperationResponse,
        flatResponse: unknown
      ) => {
        currentRawResponse = rawResponse;
        providedCallback?.(rawResponse, flatResponse);
      };
      const updatedArgs = {
        ...args,
        options: {
          ...args.options,
          onResponse: callback
        }
      };
      const flatResponse = await directSendOperation(updatedArgs, spec);
      return {
        flatResponse,
        rawResponse: {
          statusCode: currentRawResponse!.status,
          body: currentRawResponse!.parsedBody,
          headers: currentRawResponse!.headers.toJSON()
        }
      };
    };

    const lro = new LroImpl(
      sendOperation,
      { resourceGroupName, virtualMachineName, name, options },
      deleteOperationSpec
    );
    const poller = new LroEngine(lro, {
      resumeFrom: options?.resumeFrom,
      intervalInMs: options?.updateIntervalInMs
    });
    await poller.poll();
    return poller;
  }

  /**
   * Implements GuestAgent DELETE method.
   * @param resourceGroupName The Resource Group Name.
   * @param virtualMachineName Name of the vm.
   * @param name Name of the GuestAgent.
   * @param options The options parameters.
   */
  async beginDeleteAndWait(
    resourceGroupName: string,
    virtualMachineName: string,
    name: string,
    options?: GuestAgentsDeleteOptionalParams
  ): Promise<void> {
    const poller = await this.beginDelete(
      resourceGroupName,
      virtualMachineName,
      name,
      options
    );
    return poller.pollUntilDone();
  }

  /**
   * Returns the list of GuestAgent of the given vm.
   * @param resourceGroupName The Resource Group Name.
   * @param virtualMachineName Name of the vm.
   * @param options The options parameters.
   */
  private _list(
    resourceGroupName: string,
    virtualMachineName: string,
    options?: GuestAgentsListOptionalParams
  ): Promise<GuestAgentsListResponse> {
    return this.client.sendOperationRequest(
      { resourceGroupName, virtualMachineName, options },
      listOperationSpec
    );
  }

  /**
   * ListNext
   * @param resourceGroupName The Resource Group Name.
   * @param virtualMachineName Name of the vm.
   * @param nextLink The nextLink from the previous successful call to the List method.
   * @param options The options parameters.
   */
  private _listNext(
    resourceGroupName: string,
    virtualMachineName: string,
    nextLink: string,
    options?: GuestAgentsListNextOptionalParams
  ): Promise<GuestAgentsListNextResponse> {
    return this.client.sendOperationRequest(
      { resourceGroupName, virtualMachineName, nextLink, options },
      listNextOperationSpec
    );
  }
}
// Operation Specifications
const serializer = coreClient.createSerializer(Mappers, /* isXml */ false);

const createOperationSpec: coreClient.OperationSpec = {
  path:
    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ConnectedVMwarevSphere/virtualMachines/{virtualMachineName}/guestAgents/{name}",
  httpMethod: "PUT",
  responses: {
    200: {
      bodyMapper: Mappers.GuestAgent
    },
    201: {
      bodyMapper: Mappers.GuestAgent
    },
    202: {
      bodyMapper: Mappers.GuestAgent
    },
    204: {
      bodyMapper: Mappers.GuestAgent
    },
    default: {
      bodyMapper: Mappers.ErrorResponse
    }
  },
  requestBody: Parameters.body13,
  queryParameters: [Parameters.apiVersion],
  urlParameters: [
    Parameters.$host,
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.virtualMachineName,
    Parameters.name
  ],
  headerParameters: [Parameters.accept, Parameters.contentType],
  mediaType: "json",
  serializer
};
const getOperationSpec: coreClient.OperationSpec = {
  path:
    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ConnectedVMwarevSphere/virtualMachines/{virtualMachineName}/guestAgents/{name}",
  httpMethod: "GET",
  responses: {
    200: {
      bodyMapper: Mappers.GuestAgent
    },
    default: {
      bodyMapper: Mappers.ErrorResponse
    }
  },
  queryParameters: [Parameters.apiVersion],
  urlParameters: [
    Parameters.$host,
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.virtualMachineName,
    Parameters.name
  ],
  headerParameters: [Parameters.accept],
  serializer
};
const deleteOperationSpec: coreClient.OperationSpec = {
  path:
    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ConnectedVMwarevSphere/virtualMachines/{virtualMachineName}/guestAgents/{name}",
  httpMethod: "DELETE",
  responses: {
    200: {},
    201: {},
    202: {},
    204: {},
    default: {
      bodyMapper: Mappers.ErrorResponse
    }
  },
  queryParameters: [Parameters.apiVersion],
  urlParameters: [
    Parameters.$host,
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.virtualMachineName,
    Parameters.name
  ],
  headerParameters: [Parameters.accept],
  serializer
};
const listOperationSpec: coreClient.OperationSpec = {
  path:
    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ConnectedVMwarevSphere/virtualMachines/{virtualMachineName}/guestAgents",
  httpMethod: "GET",
  responses: {
    200: {
      bodyMapper: Mappers.GuestAgentList
    },
    default: {
      bodyMapper: Mappers.ErrorResponse
    }
  },
  queryParameters: [Parameters.apiVersion],
  urlParameters: [
    Parameters.$host,
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.virtualMachineName
  ],
  headerParameters: [Parameters.accept],
  serializer
};
const listNextOperationSpec: coreClient.OperationSpec = {
  path: "{nextLink}",
  httpMethod: "GET",
  responses: {
    200: {
      bodyMapper: Mappers.GuestAgentList
    },
    default: {
      bodyMapper: Mappers.ErrorResponse
    }
  },
  queryParameters: [Parameters.apiVersion],
  urlParameters: [
    Parameters.$host,
    Parameters.nextLink,
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.virtualMachineName
  ],
  headerParameters: [Parameters.accept],
  serializer
};
