// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

export interface AzureKeyVaultOutput extends ProxyResourceOutput {
  properties?: AzureKeyVaultPropertiesOutput;
}

export interface AzureKeyVaultPropertiesOutput
  extends AzureKeyVaultPropertiesAutoGeneratedOutput {}

export interface AzureKeyVaultPropertiesAutoGeneratedOutput {
  baseUrl?: string;
  description?: string;
}

export interface ProxyResourceOutput {
  id?: string;
  name?: string;
}

export interface ErrorResponseModelOutput {
  error?: ErrorResponseModelErrorOutput;
}

export interface ErrorResponseModelErrorOutput extends ErrorModelOutput {}

export interface ErrorModelOutput {
  code?: string;
  message?: string;
  target?: string;
  details?: Array<ErrorModelOutput>;
}

export interface AzureKeyVaultListOutput {
  value?: Array<AzureKeyVaultOutput>;
  nextLink?: string;
  count?: number;
}

export interface ClassificationRuleOutputBase extends ProxyResourceOutput {
  kind: "ClassificationRule" | "System" | "Custom";
}

export interface ClassificationRuleListOutput {
  value?: Array<ClassificationRuleOutput>;
  nextLink?: string;
  count?: number;
}

export interface OperationResponseOutput {
  /** Value may contain a UUID */
  scanResultId?: string;
  startTime?: string;
  endTime?: string;
  status?:
    | "Accepted"
    | "InProgress"
    | "TransientFailure"
    | "Succeeded"
    | "Failed"
    | "Canceled";
  error?: OperationResponseErrorOutput;
}

export interface OperationResponseErrorOutput extends ErrorInfoOutput {}

export interface ErrorInfoOutput {
  code?: string;
  message?: string;
  target?: string;
  details?: Array<ErrorInfoOutput>;
}

export interface DataSourceOutputBase extends ProxyResourceOutput {
  scans?: Array<ScanOutput>;
  kind:
    | "DataSource"
    | "AzureSubscription"
    | "AzureResourceGroup"
    | "AzureSynapseWorkspace"
    | "AzureSynapse"
    | "AdlsGen1"
    | "AdlsGen2"
    | "AmazonAccount"
    | "AmazonS3"
    | "AmazonSql"
    | "AzureCosmosDb"
    | "AzureDataExplorer"
    | "AzureFileService"
    | "AzureSqlDatabase"
    | "AmazonPostgreSql"
    | "AzurePostgreSql"
    | "SqlServerDatabase"
    | "AzureSqlDatabaseManagedInstance"
    | "AzureSqlDataWarehouse"
    | "AzureMySql"
    | "AzureStorage"
    | "Teradata"
    | "Oracle"
    | "SapS4Hana"
    | "SapEcc"
    | "PowerBI";
}

export interface ScanOutputBase extends ProxyResourceOutput {
  scanResults?: Array<ScanResultOutput>;
  kind:
    | "Scan"
    | "AzureSubscriptionCredential"
    | "AzureSubscriptionMsi"
    | "AzureResourceGroupCredential"
    | "AzureResourceGroupMsi"
    | "AzureSynapseWorkspaceCredential"
    | "AzureSynapseWorkspaceMsi"
    | "AzureSynapseCredential"
    | "AzureSynapseMsi"
    | "AdlsGen1Credential"
    | "AdlsGen1Msi"
    | "AdlsGen2Credential"
    | "AdlsGen2Msi"
    | "AmazonAccountCredential"
    | "AmazonS3Credential"
    | "AmazonS3RoleARN"
    | "AmazonSqlCredential"
    | "AzureCosmosDbCredential"
    | "AzureDataExplorerCredential"
    | "AzureDataExplorerMsi"
    | "AzureFileServiceCredential"
    | "AzureSqlDatabaseCredential"
    | "AzureSqlDatabaseMsi"
    | "AmazonPostgreSqlCredential"
    | "AzurePostgreSqlCredential"
    | "SqlServerDatabaseCredential"
    | "AzureSqlDatabaseManagedInstanceCredential"
    | "AzureSqlDatabaseManagedInstanceMsi"
    | "AzureSqlDataWarehouseCredential"
    | "AzureSqlDataWarehouseMsi"
    | "AzureMySqlCredential"
    | "AzureStorageCredential"
    | "AzureStorageMsi"
    | "TeradataTeradataCredential"
    | "TeradataUserPass"
    | "TeradataTeradataUserPass"
    | "OracleOracleCredential"
    | "OracleOracleUserPass"
    | "SapS4HanaSapS4HanaCredential"
    | "SapS4HanaSapS4HanaUserPass"
    | "SapEccSapEccCredential"
    | "SapEccSapEccUserPass"
    | "PowerBIDelegated"
    | "PowerBIMsi";
}

export interface ScanResultOutput {
  parentId?: string;
  id?: string;
  resourceId?: string;
  status?: string;
  assetsDiscovered?: number;
  assetsClassified?: number;
  diagnostics?: ScanResultDiagnosticsOutput;
  startTime?: string;
  queuedTime?: string;
  pipelineStartTime?: string;
  endTime?: string;
  scanRulesetVersion?: number;
  scanRulesetType?: "Custom" | "System";
  scanLevelType?: "Full" | "Incremental";
  errorMessage?: string;
  error?: ScanResultErrorOutput;
  runType?: string;
  dataSourceType?:
    | "None"
    | "AzureSubscription"
    | "AzureResourceGroup"
    | "AzureSynapseWorkspace"
    | "AzureSynapse"
    | "AdlsGen1"
    | "AdlsGen2"
    | "AmazonAccount"
    | "AmazonS3"
    | "AmazonSql"
    | "AzureCosmosDb"
    | "AzureDataExplorer"
    | "AzureFileService"
    | "AzureSqlDatabase"
    | "AmazonPostgreSql"
    | "AzurePostgreSql"
    | "SqlServerDatabase"
    | "AzureSqlDatabaseManagedInstance"
    | "AzureSqlDataWarehouse"
    | "AzureMySql"
    | "AzureStorage"
    | "Teradata"
    | "Oracle"
    | "SapS4Hana"
    | "SapEcc"
    | "PowerBI";
}

export interface ScanResultDiagnosticsOutput extends ScanDiagnosticsOutput {}

export interface ScanDiagnosticsOutput {
  notifications?: Array<NotificationOutput>;
  /** Dictionary of <integer> */
  exceptionCountMap?: Record<string, number>;
}

export interface NotificationOutput {
  message?: string;
  code?: number;
}

export interface ScanResultErrorOutput extends ErrorModelOutput {}

export interface DataSourceListOutput {
  value?: Array<DataSourceOutput>;
  nextLink?: string;
  count?: number;
}

export interface FilterOutput extends ProxyResourceOutput {
  properties?: FilterPropertiesOutput;
}

export interface FilterPropertiesOutput
  extends FilterPropertiesAutoGeneratedOutput {}

export interface FilterPropertiesAutoGeneratedOutput {
  excludeUriPrefixes?: Array<string>;
  includeUriPrefixes?: Array<string>;
}

export interface ScanListOutput {
  value?: Array<ScanOutput>;
  nextLink?: string;
  count?: number;
}

export interface ScanHistoryListOutput {
  value?: Array<ScanResultOutput>;
  nextLink?: string;
  count?: number;
}

export interface ScanRulesetOutputBase extends VersionedScanRulesetOutput {
  kind:
    | "ScanRuleset"
    | "AzureSubscription"
    | "AzureResourceGroup"
    | "AzureSynapseWorkspace"
    | "AzureSynapse"
    | "AdlsGen1"
    | "AdlsGen2"
    | "AmazonAccount"
    | "AmazonS3"
    | "AmazonSql"
    | "AzureCosmosDb"
    | "AzureDataExplorer"
    | "AzureFileService"
    | "AzureSqlDatabase"
    | "AmazonPostgreSql"
    | "AzurePostgreSql"
    | "SqlServerDatabase"
    | "AzureSqlDatabaseManagedInstance"
    | "AzureSqlDataWarehouse"
    | "AzureMySql"
    | "AzureStorage"
    | "Teradata"
    | "Oracle"
    | "SapS4Hana"
    | "SapEcc"
    | "PowerBI";
}

export interface VersionedScanRulesetOutput extends ProxyResourceOutput {
  scanRulesetType?: "Custom" | "System";
  status?: "Enabled" | "Disabled";
  version?: number;
}

export interface ScanRulesetListOutput {
  value?: Array<ScanRulesetOutput>;
  nextLink?: string;
  count?: number;
}

export interface SystemScanRulesetListOutput {
  value?: Array<SystemScanRulesetOutput>;
  nextLink?: string;
  count?: number;
}

export interface SystemScanRulesetOutputBase
  extends VersionedScanRulesetOutput {
  kind: "SystemScanRuleset" | "None";
}

export interface TriggerOutput extends ProxyResourceOutput {
  properties?: TriggerPropertiesOutput;
}

export interface TriggerPropertiesOutput
  extends TriggerPropertiesAutoGeneratedOutput {}

export interface TriggerPropertiesAutoGeneratedOutput {
  recurrence?: TriggerPropertiesRecurrenceOutput;
  recurrenceInterval?: string;
  createdAt?: string;
  lastModifiedAt?: string;
  lastScheduled?: string;
  scanLevel?: "Full" | "Incremental";
  incrementalScanStartTime?: string;
}

export interface TriggerPropertiesRecurrenceOutput
  extends TriggerRecurrenceOutput {}

export interface TriggerRecurrenceOutput {
  frequency?: "Week" | "Month";
  interval?: number;
  startTime?: string;
  endTime?: string;
  schedule?: TriggerRecurrenceScheduleOutput;
  timeZone?: string;
}

export interface TriggerRecurrenceScheduleOutput
  extends RecurrenceScheduleOutput {}

export interface RecurrenceScheduleOutput {
  /** Dictionary of <AnyObject> */
  additionalProperties?: Record<string, Record<string, unknown>>;
  minutes?: Array<number>;
  hours?: Array<number>;
  weekDays?: Array<
    | "Sunday"
    | "Monday"
    | "Tuesday"
    | "Wednesday"
    | "Thursday"
    | "Friday"
    | "Saturday"
  >;
  monthDays?: Array<number>;
  monthlyOccurrences?: Array<RecurrenceScheduleOccurrenceOutput>;
}

export interface RecurrenceScheduleOccurrenceOutput {
  /** Dictionary of <AnyObject> */
  additionalProperties?: Record<string, Record<string, unknown>>;
  day?:
    | "Sunday"
    | "Monday"
    | "Tuesday"
    | "Wednesday"
    | "Thursday"
    | "Friday"
    | "Saturday";
  occurrence?: number;
}

export interface CollectionReferenceOutput {
  lastModifiedAt?: string;
  referenceName?: string;
  type?: string;
}

export interface SystemClassificationRulePropertiesOutput {
  description?: string;
  version?: number;
  classificationName?: string;
  ruleStatus?: "Enabled" | "Disabled";
  createdAt?: string;
  lastModifiedAt?: string;
}

export interface SystemClassificationRuleOutput
  extends ClassificationRuleOutputBase {
  properties?: SystemClassificationRulePropertiesAutoGeneratedOutput;
  kind: "System";
}

export interface SystemClassificationRulePropertiesAutoGeneratedOutput
  extends SystemClassificationRulePropertiesOutput {}

export interface ClassificationRulePatternOutputBase {
  kind: "Regex";
}

export interface CustomClassificationRulePropertiesOutput {
  minimumPercentageMatch?: number;
  classificationAction?: "Keep" | "Delete";
  dataPatterns?: Array<ClassificationRulePatternOutput>;
  columnPatterns?: Array<ClassificationRulePatternOutput>;
  description?: string;
  version?: number;
  classificationName?: string;
  ruleStatus?: "Enabled" | "Disabled";
  createdAt?: string;
  lastModifiedAt?: string;
}

export interface CustomClassificationRuleOutput
  extends ClassificationRuleOutputBase {
  properties?: CustomClassificationRulePropertiesAutoGeneratedOutput;
  kind: "Custom";
}

export interface CustomClassificationRulePropertiesAutoGeneratedOutput
  extends CustomClassificationRulePropertiesOutput {}

export interface RegexClassificationRulePatternOutput
  extends ClassificationRulePatternOutputBase {
  pattern?: string;
  kind: "Regex";
}

export interface DataSourcePropertiesOutput {
  createdAt?: string;
  lastModifiedAt?: string;
  collection?: DataSourcePropertiesCollectionOutput;
}

export interface DataSourcePropertiesCollectionOutput
  extends CollectionReferenceOutput {}

export interface AzureSubscriptionPropertiesOutput
  extends DataSourcePropertiesOutput {
  subscriptionId?: string;
}

export interface AzureSubscriptionDataSourceOutput
  extends DataSourceOutputBase {
  properties?: AzureSubscriptionDataSourcePropertiesOutput;
  kind: "AzureSubscription";
}

export interface AzureSubscriptionDataSourcePropertiesOutput
  extends AzureSubscriptionPropertiesOutput {}

export interface AzureResourceGroupPropertiesOutput
  extends DataSourcePropertiesOutput {
  subscriptionId?: string;
  resourceGroup?: string;
}

export interface AzureResourceGroupDataSourceOutput
  extends DataSourceOutputBase {
  properties?: AzureResourceGroupDataSourcePropertiesOutput;
  kind: "AzureResourceGroup";
}

export interface AzureResourceGroupDataSourcePropertiesOutput
  extends AzureResourceGroupPropertiesOutput {}

export interface AzureDataSourcePropertiesOutput
  extends DataSourcePropertiesOutput {
  resourceGroup?: string;
  subscriptionId?: string;
  location?: string;
  resourceName?: string;
}

export interface AzureSynapseWorkspacePropertiesOutput
  extends AzureDataSourcePropertiesOutput {
  dedicatedSqlEndpoint?: string;
  serverlessSqlEndpoint?: string;
}

export interface AzureSynapseWorkspaceDataSourceOutput
  extends DataSourceOutputBase {
  properties?: AzureSynapseWorkspaceDataSourcePropertiesOutput;
  kind: "AzureSynapseWorkspace";
}

export interface AzureSynapseWorkspaceDataSourcePropertiesOutput
  extends AzureSynapseWorkspacePropertiesOutput {}

export interface AzureSynapsePropertiesOutput
  extends AzureDataSourcePropertiesOutput {
  sqlEndpoint?: string;
  sqlOnDemandEndpoint?: string;
}

export interface AzureSynapseDataSourceOutput extends DataSourceOutputBase {
  properties?: AzureSynapseDataSourcePropertiesOutput;
  kind: "AzureSynapse";
}

export interface AzureSynapseDataSourcePropertiesOutput
  extends AzureSynapsePropertiesOutput {}

export interface AdlsGen1PropertiesOutput
  extends AzureDataSourcePropertiesOutput {
  endpoint?: string;
}

export interface AdlsGen1DataSourceOutput extends DataSourceOutputBase {
  properties?: AdlsGen1DataSourcePropertiesOutput;
  kind: "AdlsGen1";
}

export interface AdlsGen1DataSourcePropertiesOutput
  extends AdlsGen1PropertiesOutput {}

export interface AdlsGen2PropertiesOutput
  extends AzureDataSourcePropertiesOutput {
  endpoint?: string;
}

export interface AdlsGen2DataSourceOutput extends DataSourceOutputBase {
  properties?: AdlsGen2DataSourcePropertiesOutput;
  kind: "AdlsGen2";
}

export interface AdlsGen2DataSourcePropertiesOutput
  extends AdlsGen2PropertiesOutput {}

export interface AmazonAccountPropertiesOutput
  extends DataSourcePropertiesOutput {
  awsAccountId?: string;
  roleARN?: string;
}

export interface AmazonAccountDataSourceOutput extends DataSourceOutputBase {
  properties?: AmazonAccountDataSourcePropertiesOutput;
  kind: "AmazonAccount";
}

export interface AmazonAccountDataSourcePropertiesOutput
  extends AmazonAccountPropertiesOutput {}

export interface AmazonS3PropertiesOutput extends DataSourcePropertiesOutput {
  serviceUrl?: string;
  roleARN?: string;
}

export interface AmazonS3DataSourceOutput extends DataSourceOutputBase {
  properties?: AmazonS3DataSourcePropertiesOutput;
  kind: "AmazonS3";
}

export interface AmazonS3DataSourcePropertiesOutput
  extends AmazonS3PropertiesOutput {}

export interface AmazonSqlPropertiesOutput extends DataSourcePropertiesOutput {
  serverEndpoint?: string;
}

export interface AmazonSqlDataSourceOutput extends DataSourceOutputBase {
  properties?: AmazonSqlDataSourcePropertiesOutput;
  kind: "AmazonSql";
}

export interface AmazonSqlDataSourcePropertiesOutput
  extends AmazonSqlPropertiesOutput {}

export interface AzureCosmosDbPropertiesOutput
  extends AzureDataSourcePropertiesOutput {
  accountUri?: string;
}

export interface AzureCosmosDbDataSourceOutput extends DataSourceOutputBase {
  properties?: AzureCosmosDbDataSourcePropertiesOutput;
  kind: "AzureCosmosDb";
}

export interface AzureCosmosDbDataSourcePropertiesOutput
  extends AzureCosmosDbPropertiesOutput {}

export interface AzureDataExplorerPropertiesOutput
  extends AzureDataSourcePropertiesOutput {
  endpoint?: string;
}

export interface AzureDataExplorerDataSourceOutput
  extends DataSourceOutputBase {
  properties?: AzureDataExplorerDataSourcePropertiesOutput;
  kind: "AzureDataExplorer";
}

export interface AzureDataExplorerDataSourcePropertiesOutput
  extends AzureDataExplorerPropertiesOutput {}

export interface AzureFileServicePropertiesOutput
  extends AzureDataSourcePropertiesOutput {
  endpoint?: string;
}

export interface AzureFileServiceDataSourceOutput extends DataSourceOutputBase {
  properties?: AzureFileServiceDataSourcePropertiesOutput;
  kind: "AzureFileService";
}

export interface AzureFileServiceDataSourcePropertiesOutput
  extends AzureFileServicePropertiesOutput {}

export interface AzureSqlDatabasePropertiesOutput
  extends AzureDataSourcePropertiesOutput {
  serverEndpoint?: string;
}

export interface AzureSqlDatabaseDataSourceOutput extends DataSourceOutputBase {
  properties?: AzureSqlDatabaseDataSourcePropertiesOutput;
  kind: "AzureSqlDatabase";
}

export interface AzureSqlDatabaseDataSourcePropertiesOutput
  extends AzureSqlDatabasePropertiesOutput {}

export interface AmazonPostgreSqlPropertiesOutput
  extends DataSourcePropertiesOutput {
  serverEndpoint?: string;
  port?: string;
}

export interface AmazonPostgreSqlDataSourceOutput extends DataSourceOutputBase {
  properties?: AmazonPostgreSqlDataSourcePropertiesOutput;
  kind: "AmazonPostgreSql";
}

export interface AmazonPostgreSqlDataSourcePropertiesOutput
  extends AmazonPostgreSqlPropertiesOutput {}

export interface AzurePostgreSqlPropertiesOutput
  extends AzureDataSourcePropertiesOutput {
  serverEndpoint?: string;
  port?: number;
}

export interface AzurePostgreSqlDataSourceOutput extends DataSourceOutputBase {
  properties?: AzurePostgreSqlDataSourcePropertiesOutput;
  kind: "AzurePostgreSql";
}

export interface AzurePostgreSqlDataSourcePropertiesOutput
  extends AzurePostgreSqlPropertiesOutput {}

export interface SqlServerDatabasePropertiesOutput
  extends AzureDataSourcePropertiesOutput {
  serverEndpoint?: string;
}

export interface SqlServerDatabaseDataSourceOutput
  extends DataSourceOutputBase {
  properties?: SqlServerDatabaseDataSourcePropertiesOutput;
  kind: "SqlServerDatabase";
}

export interface SqlServerDatabaseDataSourcePropertiesOutput
  extends SqlServerDatabasePropertiesOutput {}

export interface AzureSqlDatabaseManagedInstancePropertiesOutput
  extends AzureDataSourcePropertiesOutput {
  serverEndpoint?: string;
}

export interface AzureSqlDatabaseManagedInstanceDataSourceOutput
  extends DataSourceOutputBase {
  properties?: AzureSqlDatabaseManagedInstanceDataSourcePropertiesOutput;
  kind: "AzureSqlDatabaseManagedInstance";
}

export interface AzureSqlDatabaseManagedInstanceDataSourcePropertiesOutput
  extends AzureSqlDatabaseManagedInstancePropertiesOutput {}

export interface AzureSqlDataWarehousePropertiesOutput
  extends AzureDataSourcePropertiesOutput {
  serverEndpoint?: string;
}

export interface AzureSqlDataWarehouseDataSourceOutput
  extends DataSourceOutputBase {
  properties?: AzureSqlDataWarehouseDataSourcePropertiesOutput;
  kind: "AzureSqlDataWarehouse";
}

export interface AzureSqlDataWarehouseDataSourcePropertiesOutput
  extends AzureSqlDataWarehousePropertiesOutput {}

export interface AzureMySqlPropertiesOutput
  extends AzureDataSourcePropertiesOutput {
  serverEndpoint?: string;
  port?: number;
}

export interface AzureMySqlDataSourceOutput extends DataSourceOutputBase {
  properties?: AzureMySqlDataSourcePropertiesOutput;
  kind: "AzureMySql";
}

export interface AzureMySqlDataSourcePropertiesOutput
  extends AzureMySqlPropertiesOutput {}

export interface AzureStoragePropertiesOutput
  extends AzureDataSourcePropertiesOutput {
  endpoint?: string;
}

export interface AzureStorageDataSourceOutput extends DataSourceOutputBase {
  properties?: AzureStorageDataSourcePropertiesOutput;
  kind: "AzureStorage";
}

export interface AzureStorageDataSourcePropertiesOutput
  extends AzureStoragePropertiesOutput {}

export interface TeradataPropertiesOutput extends DataSourcePropertiesOutput {
  host?: string;
}

export interface TeradataDataSourceOutput extends DataSourceOutputBase {
  properties?: TeradataDataSourcePropertiesOutput;
  kind: "Teradata";
}

export interface TeradataDataSourcePropertiesOutput
  extends TeradataPropertiesOutput {}

export interface OraclePropertiesOutput extends DataSourcePropertiesOutput {
  host?: string;
  port?: string;
  service?: string;
}

export interface OracleDataSourceOutput extends DataSourceOutputBase {
  properties?: OracleDataSourcePropertiesOutput;
  kind: "Oracle";
}

export interface OracleDataSourcePropertiesOutput
  extends OraclePropertiesOutput {}

export interface SapS4HanaPropertiesOutput extends DataSourcePropertiesOutput {
  applicationServer?: string;
  systemNumber?: string;
}

export interface SapS4HanaDataSourceOutput extends DataSourceOutputBase {
  properties?: SapS4HanaDataSourcePropertiesOutput;
  kind: "SapS4Hana";
}

export interface SapS4HanaDataSourcePropertiesOutput
  extends SapS4HanaPropertiesOutput {}

export interface SapEccPropertiesOutput extends DataSourcePropertiesOutput {
  applicationServer?: string;
  systemNumber?: string;
}

export interface SapEccDataSourceOutput extends DataSourceOutputBase {
  properties?: SapEccDataSourcePropertiesOutput;
  kind: "SapEcc";
}

export interface SapEccDataSourcePropertiesOutput
  extends SapEccPropertiesOutput {}

export interface PowerBIPropertiesOutput extends DataSourcePropertiesOutput {
  tenant?: string;
}

export interface PowerBIDataSourceOutput extends DataSourceOutputBase {
  properties?: PowerBIDataSourcePropertiesOutput;
  kind: "PowerBI";
}

export interface PowerBIDataSourcePropertiesOutput
  extends PowerBIPropertiesOutput {}

export interface ScanRulesetPropertiesOutput {
  createdAt?: string;
  description?: string;
  excludedSystemClassifications?: Array<string>;
  includedCustomClassificationRuleNames?: Array<string>;
  lastModifiedAt?: string;
}

export interface AzureSubscriptionScanRulesetPropertiesOutput
  extends ScanRulesetPropertiesOutput {}

export interface AzureSubscriptionScanRulesetOutput
  extends ScanRulesetOutputBase {
  properties?: AzureSubscriptionScanRulesetPropertiesAutoGeneratedOutput;
  kind: "AzureSubscription";
}

export interface AzureSubscriptionScanRulesetPropertiesAutoGeneratedOutput
  extends AzureSubscriptionScanRulesetPropertiesOutput {}

export interface AzureResourceGroupScanRulesetPropertiesOutput
  extends ScanRulesetPropertiesOutput {}

export interface AzureResourceGroupScanRulesetOutput
  extends ScanRulesetOutputBase {
  properties?: AzureResourceGroupScanRulesetPropertiesAutoGeneratedOutput;
  kind: "AzureResourceGroup";
}

export interface AzureResourceGroupScanRulesetPropertiesAutoGeneratedOutput
  extends AzureResourceGroupScanRulesetPropertiesOutput {}

export interface AzureSynapseWorkspaceScanRulesetPropertiesOutput
  extends ScanRulesetPropertiesOutput {}

export interface AzureSynapseWorkspaceScanRulesetOutput
  extends ScanRulesetOutputBase {
  properties?: AzureSynapseWorkspaceScanRulesetPropertiesAutoGeneratedOutput;
  kind: "AzureSynapseWorkspace";
}

export interface AzureSynapseWorkspaceScanRulesetPropertiesAutoGeneratedOutput
  extends AzureSynapseWorkspaceScanRulesetPropertiesOutput {}

export interface AzureSynapseScanRulesetPropertiesOutput
  extends ScanRulesetPropertiesOutput {}

export interface AzureSynapseScanRulesetOutput extends ScanRulesetOutputBase {
  properties?: AzureSynapseScanRulesetPropertiesAutoGeneratedOutput;
  kind: "AzureSynapse";
}

export interface AzureSynapseScanRulesetPropertiesAutoGeneratedOutput
  extends AzureSynapseScanRulesetPropertiesOutput {}

export interface CustomFileTypeOutput {
  builtInType?:
    | "AVRO"
    | "ORC"
    | "PARQUET"
    | "JSON"
    | "TXT"
    | "XML"
    | "Documents"
    | "CSV"
    | "PSV"
    | "SSV"
    | "TSV"
    | "GZ"
    | "DOC"
    | "DOCM"
    | "DOCX"
    | "DOT"
    | "ODP"
    | "ODS"
    | "ODT"
    | "PDF"
    | "POT"
    | "PPS"
    | "PPSX"
    | "PPT"
    | "PPTM"
    | "PPTX"
    | "XLC"
    | "XLS"
    | "XLSB"
    | "XLSM"
    | "XLSX"
    | "XLT";
  customDelimiter?: string;
}

export interface CustomFileExtensionOutput {
  customFileType?: CustomFileExtensionCustomFileTypeOutput;
  description?: string;
  enabled?: boolean;
  fileExtension?: string;
}

export interface CustomFileExtensionCustomFileTypeOutput
  extends CustomFileTypeOutput {}

export interface ScanningRuleOutput {
  fileExtensions?: Array<
    | "AVRO"
    | "ORC"
    | "PARQUET"
    | "JSON"
    | "TXT"
    | "XML"
    | "Documents"
    | "CSV"
    | "PSV"
    | "SSV"
    | "TSV"
    | "GZ"
    | "DOC"
    | "DOCM"
    | "DOCX"
    | "DOT"
    | "ODP"
    | "ODS"
    | "ODT"
    | "PDF"
    | "POT"
    | "PPS"
    | "PPSX"
    | "PPT"
    | "PPTM"
    | "PPTX"
    | "XLC"
    | "XLS"
    | "XLSB"
    | "XLSM"
    | "XLSX"
    | "XLT"
  >;
  customFileExtensions?: Array<CustomFileExtensionOutput>;
}

export interface ScanningRuleScanRulesetPropertiesOutput
  extends ScanRulesetPropertiesOutput {
  scanningRule?: ScanningRuleScanRulesetPropertiesScanningRuleOutput;
}

export interface ScanningRuleScanRulesetPropertiesScanningRuleOutput
  extends ScanningRuleOutput {}

export interface AdlsGen1ScanRulesetPropertiesOutput
  extends ScanningRuleScanRulesetPropertiesOutput {}

export interface AdlsGen1ScanRulesetOutput extends ScanRulesetOutputBase {
  properties?: AdlsGen1ScanRulesetPropertiesAutoGeneratedOutput;
  kind: "AdlsGen1";
}

export interface AdlsGen1ScanRulesetPropertiesAutoGeneratedOutput
  extends AdlsGen1ScanRulesetPropertiesOutput {}

export interface AdlsGen2ScanRulesetPropertiesOutput
  extends ScanningRuleScanRulesetPropertiesOutput {}

export interface AdlsGen2ScanRulesetOutput extends ScanRulesetOutputBase {
  properties?: AdlsGen2ScanRulesetPropertiesAutoGeneratedOutput;
  kind: "AdlsGen2";
}

export interface AdlsGen2ScanRulesetPropertiesAutoGeneratedOutput
  extends AdlsGen2ScanRulesetPropertiesOutput {}

export interface AmazonAccountScanRulesetPropertiesOutput
  extends ScanRulesetPropertiesOutput {}

export interface AmazonAccountScanRulesetOutput extends ScanRulesetOutputBase {
  properties?: AmazonAccountScanRulesetPropertiesAutoGeneratedOutput;
  kind: "AmazonAccount";
}

export interface AmazonAccountScanRulesetPropertiesAutoGeneratedOutput
  extends AmazonAccountScanRulesetPropertiesOutput {}

export interface AmazonS3ScanRulesetPropertiesOutput
  extends ScanningRuleScanRulesetPropertiesOutput {}

export interface AmazonS3ScanRulesetOutput extends ScanRulesetOutputBase {
  properties?: AmazonS3ScanRulesetPropertiesAutoGeneratedOutput;
  kind: "AmazonS3";
}

export interface AmazonS3ScanRulesetPropertiesAutoGeneratedOutput
  extends AmazonS3ScanRulesetPropertiesOutput {}

export interface AmazonSqlScanRulesetPropertiesOutput
  extends ScanRulesetPropertiesOutput {}

export interface AmazonSqlScanRulesetOutput extends ScanRulesetOutputBase {
  properties?: AmazonSqlScanRulesetPropertiesAutoGeneratedOutput;
  kind: "AmazonSql";
}

export interface AmazonSqlScanRulesetPropertiesAutoGeneratedOutput
  extends AmazonSqlScanRulesetPropertiesOutput {}

export interface AzureCosmosDbScanRulesetPropertiesOutput
  extends ScanRulesetPropertiesOutput {}

export interface AzureCosmosDbScanRulesetOutput extends ScanRulesetOutputBase {
  properties?: AzureCosmosDbScanRulesetPropertiesAutoGeneratedOutput;
  kind: "AzureCosmosDb";
}

export interface AzureCosmosDbScanRulesetPropertiesAutoGeneratedOutput
  extends AzureCosmosDbScanRulesetPropertiesOutput {}

export interface AzureDataExplorerScanRulesetPropertiesOutput
  extends ScanRulesetPropertiesOutput {}

export interface AzureDataExplorerScanRulesetOutput
  extends ScanRulesetOutputBase {
  properties?: AzureDataExplorerScanRulesetPropertiesAutoGeneratedOutput;
  kind: "AzureDataExplorer";
}

export interface AzureDataExplorerScanRulesetPropertiesAutoGeneratedOutput
  extends AzureDataExplorerScanRulesetPropertiesOutput {}

export interface AzureFileServiceScanRulesetPropertiesOutput
  extends ScanningRuleScanRulesetPropertiesOutput {}

export interface AzureFileServiceScanRulesetOutput
  extends ScanRulesetOutputBase {
  properties?: AzureFileServiceScanRulesetPropertiesAutoGeneratedOutput;
  kind: "AzureFileService";
}

export interface AzureFileServiceScanRulesetPropertiesAutoGeneratedOutput
  extends AzureFileServiceScanRulesetPropertiesOutput {}

export interface AzureSqlDatabaseScanRulesetPropertiesOutput
  extends ScanRulesetPropertiesOutput {}

export interface AzureSqlDatabaseScanRulesetOutput
  extends ScanRulesetOutputBase {
  properties?: AzureSqlDatabaseScanRulesetPropertiesAutoGeneratedOutput;
  kind: "AzureSqlDatabase";
}

export interface AzureSqlDatabaseScanRulesetPropertiesAutoGeneratedOutput
  extends AzureSqlDatabaseScanRulesetPropertiesOutput {}

export interface AmazonPostgreSqlScanRulesetPropertiesOutput
  extends ScanRulesetPropertiesOutput {}

export interface AmazonPostgreSqlScanRulesetOutput
  extends ScanRulesetOutputBase {
  properties?: AmazonPostgreSqlScanRulesetPropertiesAutoGeneratedOutput;
  kind: "AmazonPostgreSql";
}

export interface AmazonPostgreSqlScanRulesetPropertiesAutoGeneratedOutput
  extends AmazonPostgreSqlScanRulesetPropertiesOutput {}

export interface AzurePostgreSqlScanRulesetPropertiesOutput
  extends ScanRulesetPropertiesOutput {}

export interface AzurePostgreSqlScanRulesetOutput
  extends ScanRulesetOutputBase {
  properties?: AzurePostgreSqlScanRulesetPropertiesAutoGeneratedOutput;
  kind: "AzurePostgreSql";
}

export interface AzurePostgreSqlScanRulesetPropertiesAutoGeneratedOutput
  extends AzurePostgreSqlScanRulesetPropertiesOutput {}

export interface SqlServerDatabaseScanRulesetPropertiesOutput
  extends ScanRulesetPropertiesOutput {}

export interface SqlServerDatabaseScanRulesetOutput
  extends ScanRulesetOutputBase {
  properties?: SqlServerDatabaseScanRulesetPropertiesAutoGeneratedOutput;
  kind: "SqlServerDatabase";
}

export interface SqlServerDatabaseScanRulesetPropertiesAutoGeneratedOutput
  extends SqlServerDatabaseScanRulesetPropertiesOutput {}

export interface AzureSqlDatabaseManagedInstanceScanRulesetPropertiesOutput
  extends ScanRulesetPropertiesOutput {}

export interface AzureSqlDatabaseManagedInstanceScanRulesetOutput
  extends ScanRulesetOutputBase {
  properties?: AzureSqlDatabaseManagedInstanceScanRulesetPropertiesAutoGeneratedOutput;
  kind: "AzureSqlDatabaseManagedInstance";
}

export interface AzureSqlDatabaseManagedInstanceScanRulesetPropertiesAutoGeneratedOutput
  extends AzureSqlDatabaseManagedInstanceScanRulesetPropertiesOutput {}

export interface AzureSqlDataWarehouseScanRulesetPropertiesOutput
  extends ScanRulesetPropertiesOutput {}

export interface AzureSqlDataWarehouseScanRulesetOutput
  extends ScanRulesetOutputBase {
  properties?: AzureSqlDataWarehouseScanRulesetPropertiesAutoGeneratedOutput;
  kind: "AzureSqlDataWarehouse";
}

export interface AzureSqlDataWarehouseScanRulesetPropertiesAutoGeneratedOutput
  extends AzureSqlDataWarehouseScanRulesetPropertiesOutput {}

export interface AzureMySqlScanRulesetPropertiesOutput
  extends ScanRulesetPropertiesOutput {}

export interface AzureMySqlScanRulesetOutput extends ScanRulesetOutputBase {
  properties?: AzureMySqlScanRulesetPropertiesAutoGeneratedOutput;
  kind: "AzureMySql";
}

export interface AzureMySqlScanRulesetPropertiesAutoGeneratedOutput
  extends AzureMySqlScanRulesetPropertiesOutput {}

export interface AzureStorageScanRulesetPropertiesOutput
  extends ScanningRuleScanRulesetPropertiesOutput {}

export interface AzureStorageScanRulesetOutput extends ScanRulesetOutputBase {
  properties?: AzureStorageScanRulesetPropertiesAutoGeneratedOutput;
  kind: "AzureStorage";
}

export interface AzureStorageScanRulesetPropertiesAutoGeneratedOutput
  extends AzureStorageScanRulesetPropertiesOutput {}

export interface TeradataScanRulesetPropertiesOutput
  extends ScanRulesetPropertiesOutput {}

export interface TeradataScanRulesetOutput extends ScanRulesetOutputBase {
  properties?: TeradataScanRulesetPropertiesAutoGeneratedOutput;
  kind: "Teradata";
}

export interface TeradataScanRulesetPropertiesAutoGeneratedOutput
  extends TeradataScanRulesetPropertiesOutput {}

export interface OracleScanRulesetPropertiesOutput
  extends ScanRulesetPropertiesOutput {}

export interface OracleScanRulesetOutput extends ScanRulesetOutputBase {
  properties?: OracleScanRulesetPropertiesAutoGeneratedOutput;
  kind: "Oracle";
}

export interface OracleScanRulesetPropertiesAutoGeneratedOutput
  extends OracleScanRulesetPropertiesOutput {}

export interface SapS4HanaScanRulesetPropertiesOutput
  extends ScanRulesetPropertiesOutput {}

export interface SapS4HanaScanRulesetOutput extends ScanRulesetOutputBase {
  properties?: SapS4HanaScanRulesetPropertiesAutoGeneratedOutput;
  kind: "SapS4Hana";
}

export interface SapS4HanaScanRulesetPropertiesAutoGeneratedOutput
  extends SapS4HanaScanRulesetPropertiesOutput {}

export interface SapEccScanRulesetPropertiesOutput
  extends ScanRulesetPropertiesOutput {}

export interface SapEccScanRulesetOutput extends ScanRulesetOutputBase {
  properties?: SapEccScanRulesetPropertiesAutoGeneratedOutput;
  kind: "SapEcc";
}

export interface SapEccScanRulesetPropertiesAutoGeneratedOutput
  extends SapEccScanRulesetPropertiesOutput {}

export interface PowerBIScanRulesetPropertiesOutput
  extends ScanRulesetPropertiesOutput {}

export interface PowerBIScanRulesetOutput extends ScanRulesetOutputBase {
  properties?: PowerBIScanRulesetPropertiesAutoGeneratedOutput;
  kind: "PowerBI";
}

export interface PowerBIScanRulesetPropertiesAutoGeneratedOutput
  extends PowerBIScanRulesetPropertiesOutput {}

export interface ResourceNameFilterOutput {
  excludePrefixes?: Array<string>;
  includePrefixes?: Array<string>;
  resources?: Array<string>;
}

export interface CredentialReferenceOutput {
  referenceName?: string;
  credentialType?:
    | "AccountKey"
    | "ServicePrincipal"
    | "BasicAuth"
    | "SqlAuth"
    | "AmazonARN";
}

export interface ResourceTypeFilterOutput {
  scanRulesetName?: string;
  scanRulesetType?: "Custom" | "System";
  resourceNameFilter?: ResourceTypeFilterResourceNameFilterOutput;
  credential?: ResourceTypeFilterCredentialOutput;
}

export interface ResourceTypeFilterResourceNameFilterOutput
  extends ResourceNameFilterOutput {}

export interface ResourceTypeFilterCredentialOutput
  extends CredentialReferenceOutput {}

export interface ConnectedViaOutput {
  referenceName?: string;
}

export interface ScanPropertiesOutput {
  scanRulesetName?: string;
  scanRulesetType?: "Custom" | "System";
  collection?: ScanPropertiesCollectionOutput;
  workers?: number;
  createdAt?: string;
  lastModifiedAt?: string;
  connectedVia?: ScanPropertiesConnectedViaOutput;
}

export interface ScanPropertiesCollectionOutput
  extends CollectionReferenceOutput {}

export interface ScanPropertiesConnectedViaOutput extends ConnectedViaOutput {}

export interface ExpandingResourceScanPropertiesOutput
  extends ScanPropertiesOutput {
  resourceTypes?: ExpandingResourceScanPropertiesResourceTypesOutput;
  credential?: ExpandingResourceScanPropertiesCredentialOutput;
}

export interface ExpandingResourceScanPropertiesResourceTypesOutput {
  None?: ResourceTypeFilterOutput;
  AzureSubscription?: ResourceTypeFilterOutput;
  AzureResourceGroup?: ResourceTypeFilterOutput;
  AzureSynapseWorkspace?: ResourceTypeFilterOutput;
  AzureSynapse?: ResourceTypeFilterOutput;
  AdlsGen1?: ResourceTypeFilterOutput;
  AdlsGen2?: ResourceTypeFilterOutput;
  AmazonAccount?: ResourceTypeFilterOutput;
  AmazonS3?: ResourceTypeFilterOutput;
  AmazonSql?: ResourceTypeFilterOutput;
  AzureCosmosDb?: ResourceTypeFilterOutput;
  AzureDataExplorer?: ResourceTypeFilterOutput;
  AzureFileService?: ResourceTypeFilterOutput;
  AzureSqlDatabase?: ResourceTypeFilterOutput;
  AmazonPostgreSql?: ResourceTypeFilterOutput;
  AzurePostgreSql?: ResourceTypeFilterOutput;
  SqlServerDatabase?: ResourceTypeFilterOutput;
  AzureSqlDatabaseManagedInstance?: ResourceTypeFilterOutput;
  AzureSqlDataWarehouse?: ResourceTypeFilterOutput;
  AzureMySql?: ResourceTypeFilterOutput;
  AzureStorage?: ResourceTypeFilterOutput;
  Teradata?: ResourceTypeFilterOutput;
  Oracle?: ResourceTypeFilterOutput;
  SapS4Hana?: ResourceTypeFilterOutput;
  SapEcc?: ResourceTypeFilterOutput;
  PowerBI?: ResourceTypeFilterOutput;
}

export interface ExpandingResourceScanPropertiesCredentialOutput
  extends CredentialReferenceOutput {}

export interface AzureSubscriptionCredentialScanPropertiesOutput
  extends ExpandingResourceScanPropertiesOutput {}

export interface AzureSubscriptionCredentialScanOutput extends ScanOutputBase {
  properties?: AzureSubscriptionCredentialScanPropertiesAutoGeneratedOutput;
  kind: "AzureSubscriptionCredential";
}

export interface AzureSubscriptionCredentialScanPropertiesAutoGeneratedOutput
  extends AzureSubscriptionCredentialScanPropertiesOutput {}

export interface AzureSubscriptionMsiScanPropertiesOutput
  extends ExpandingResourceScanPropertiesOutput {}

export interface AzureSubscriptionMsiScanOutput extends ScanOutputBase {
  properties?: AzureSubscriptionMsiScanPropertiesAutoGeneratedOutput;
  kind: "AzureSubscriptionMsi";
}

export interface AzureSubscriptionMsiScanPropertiesAutoGeneratedOutput
  extends AzureSubscriptionMsiScanPropertiesOutput {}

export interface AzureResourceGroupCredentialScanPropertiesOutput
  extends ExpandingResourceScanPropertiesOutput {}

export interface AzureResourceGroupCredentialScanOutput extends ScanOutputBase {
  properties?: AzureResourceGroupCredentialScanPropertiesAutoGeneratedOutput;
  kind: "AzureResourceGroupCredential";
}

export interface AzureResourceGroupCredentialScanPropertiesAutoGeneratedOutput
  extends AzureResourceGroupCredentialScanPropertiesOutput {}

export interface AzureResourceGroupMsiScanPropertiesOutput
  extends ExpandingResourceScanPropertiesOutput {}

export interface AzureResourceGroupMsiScanOutput extends ScanOutputBase {
  properties?: AzureResourceGroupMsiScanPropertiesAutoGeneratedOutput;
  kind: "AzureResourceGroupMsi";
}

export interface AzureResourceGroupMsiScanPropertiesAutoGeneratedOutput
  extends AzureResourceGroupMsiScanPropertiesOutput {}

export interface AzureSynapseWorkspaceCredentialScanPropertiesOutput
  extends ExpandingResourceScanPropertiesOutput {}

export interface AzureSynapseWorkspaceCredentialScanOutput
  extends ScanOutputBase {
  properties?: AzureSynapseWorkspaceCredentialScanPropertiesAutoGeneratedOutput;
  kind: "AzureSynapseWorkspaceCredential";
}

export interface AzureSynapseWorkspaceCredentialScanPropertiesAutoGeneratedOutput
  extends AzureSynapseWorkspaceCredentialScanPropertiesOutput {}

export interface AzureSynapseWorkspaceMsiScanPropertiesOutput
  extends ExpandingResourceScanPropertiesOutput {}

export interface AzureSynapseWorkspaceMsiScanOutput extends ScanOutputBase {
  properties?: AzureSynapseWorkspaceMsiScanPropertiesAutoGeneratedOutput;
  kind: "AzureSynapseWorkspaceMsi";
}

export interface AzureSynapseWorkspaceMsiScanPropertiesAutoGeneratedOutput
  extends AzureSynapseWorkspaceMsiScanPropertiesOutput {}

export interface AzureSynapseCredentialScanPropertiesOutput
  extends ExpandingResourceScanPropertiesOutput {}

export interface AzureSynapseCredentialScanOutput extends ScanOutputBase {
  properties?: AzureSynapseCredentialScanPropertiesAutoGeneratedOutput;
  kind: "AzureSynapseCredential";
}

export interface AzureSynapseCredentialScanPropertiesAutoGeneratedOutput
  extends AzureSynapseCredentialScanPropertiesOutput {}

export interface AzureSynapseMsiScanPropertiesOutput
  extends ExpandingResourceScanPropertiesOutput {}

export interface AzureSynapseMsiScanOutput extends ScanOutputBase {
  properties?: AzureSynapseMsiScanPropertiesAutoGeneratedOutput;
  kind: "AzureSynapseMsi";
}

export interface AzureSynapseMsiScanPropertiesAutoGeneratedOutput
  extends AzureSynapseMsiScanPropertiesOutput {}

export interface AdlsGen1CredentialScanPropertiesOutput
  extends ScanPropertiesOutput {
  credential?: AdlsGen1CredentialScanPropertiesCredentialOutput;
}

export interface AdlsGen1CredentialScanPropertiesCredentialOutput
  extends CredentialReferenceOutput {}

export interface AdlsGen1CredentialScanOutput extends ScanOutputBase {
  properties?: AdlsGen1CredentialScanPropertiesAutoGeneratedOutput;
  kind: "AdlsGen1Credential";
}

export interface AdlsGen1CredentialScanPropertiesAutoGeneratedOutput
  extends AdlsGen1CredentialScanPropertiesOutput {}

export interface AdlsGen1MsiScanPropertiesOutput extends ScanPropertiesOutput {}

export interface AdlsGen1MsiScanOutput extends ScanOutputBase {
  properties?: AdlsGen1MsiScanPropertiesAutoGeneratedOutput;
  kind: "AdlsGen1Msi";
}

export interface AdlsGen1MsiScanPropertiesAutoGeneratedOutput
  extends AdlsGen1MsiScanPropertiesOutput {}

export interface AdlsGen2CredentialScanPropertiesOutput
  extends ScanPropertiesOutput {
  credential?: AdlsGen2CredentialScanPropertiesCredentialOutput;
}

export interface AdlsGen2CredentialScanPropertiesCredentialOutput
  extends CredentialReferenceOutput {}

export interface AdlsGen2CredentialScanOutput extends ScanOutputBase {
  properties?: AdlsGen2CredentialScanPropertiesAutoGeneratedOutput;
  kind: "AdlsGen2Credential";
}

export interface AdlsGen2CredentialScanPropertiesAutoGeneratedOutput
  extends AdlsGen2CredentialScanPropertiesOutput {}

export interface AdlsGen2MsiScanPropertiesOutput extends ScanPropertiesOutput {}

export interface AdlsGen2MsiScanOutput extends ScanOutputBase {
  properties?: AdlsGen2MsiScanPropertiesAutoGeneratedOutput;
  kind: "AdlsGen2Msi";
}

export interface AdlsGen2MsiScanPropertiesAutoGeneratedOutput
  extends AdlsGen2MsiScanPropertiesOutput {}

export interface AmazonAccountCredentialScanPropertiesOutput
  extends ExpandingResourceScanPropertiesOutput {}

export interface AmazonAccountCredentialScanOutput extends ScanOutputBase {
  properties?: AmazonAccountCredentialScanPropertiesAutoGeneratedOutput;
  kind: "AmazonAccountCredential";
}

export interface AmazonAccountCredentialScanPropertiesAutoGeneratedOutput
  extends AmazonAccountCredentialScanPropertiesOutput {}

export interface AmazonS3CredentialScanPropertiesOutput
  extends ScanPropertiesOutput {
  credential?: AmazonS3CredentialScanPropertiesCredentialOutput;
  roleARN?: string;
}

export interface AmazonS3CredentialScanPropertiesCredentialOutput
  extends CredentialReferenceOutput {}

export interface AmazonS3CredentialScanOutput extends ScanOutputBase {
  properties?: AmazonS3CredentialScanPropertiesAutoGeneratedOutput;
  kind: "AmazonS3Credential";
}

export interface AmazonS3CredentialScanPropertiesAutoGeneratedOutput
  extends AmazonS3CredentialScanPropertiesOutput {}

export interface AmazonS3RoleARNScanPropertiesOutput
  extends ScanPropertiesOutput {
  roleARN?: string;
}

export interface AmazonS3RoleARNScanOutput extends ScanOutputBase {
  properties?: AmazonS3RoleARNScanPropertiesAutoGeneratedOutput;
  kind: "AmazonS3RoleARN";
}

export interface AmazonS3RoleARNScanPropertiesAutoGeneratedOutput
  extends AmazonS3RoleARNScanPropertiesOutput {}

export interface AmazonSqlCredentialScanPropertiesOutput
  extends ScanPropertiesOutput {
  credential?: AmazonSqlCredentialScanPropertiesCredentialOutput;
  serverEndpoint?: string;
  databaseName?: string;
}

export interface AmazonSqlCredentialScanPropertiesCredentialOutput
  extends CredentialReferenceOutput {}

export interface AmazonSqlCredentialScanOutput extends ScanOutputBase {
  properties?: AmazonSqlCredentialScanPropertiesAutoGeneratedOutput;
  kind: "AmazonSqlCredential";
}

export interface AmazonSqlCredentialScanPropertiesAutoGeneratedOutput
  extends AmazonSqlCredentialScanPropertiesOutput {}

export interface AzureCosmosDbCredentialScanPropertiesOutput
  extends ScanPropertiesOutput {
  credential?: AzureCosmosDbCredentialScanPropertiesCredentialOutput;
  databaseName?: string;
}

export interface AzureCosmosDbCredentialScanPropertiesCredentialOutput
  extends CredentialReferenceOutput {}

export interface AzureCosmosDbCredentialScanOutput extends ScanOutputBase {
  properties?: AzureCosmosDbCredentialScanPropertiesAutoGeneratedOutput;
  kind: "AzureCosmosDbCredential";
}

export interface AzureCosmosDbCredentialScanPropertiesAutoGeneratedOutput
  extends AzureCosmosDbCredentialScanPropertiesOutput {}

export interface AzureDataExplorerCredentialScanPropertiesOutput
  extends ScanPropertiesOutput {
  credential?: AzureDataExplorerCredentialScanPropertiesCredentialOutput;
  database?: string;
}

export interface AzureDataExplorerCredentialScanPropertiesCredentialOutput
  extends CredentialReferenceOutput {}

export interface AzureDataExplorerCredentialScanOutput extends ScanOutputBase {
  properties?: AzureDataExplorerCredentialScanPropertiesAutoGeneratedOutput;
  kind: "AzureDataExplorerCredential";
}

export interface AzureDataExplorerCredentialScanPropertiesAutoGeneratedOutput
  extends AzureDataExplorerCredentialScanPropertiesOutput {}

export interface AzureDataExplorerMsiScanPropertiesOutput
  extends ScanPropertiesOutput {
  database?: string;
}

export interface AzureDataExplorerMsiScanOutput extends ScanOutputBase {
  properties?: AzureDataExplorerMsiScanPropertiesAutoGeneratedOutput;
  kind: "AzureDataExplorerMsi";
}

export interface AzureDataExplorerMsiScanPropertiesAutoGeneratedOutput
  extends AzureDataExplorerMsiScanPropertiesOutput {}

export interface AzureFileServiceCredentialScanPropertiesOutput
  extends ScanPropertiesOutput {
  credential?: AzureFileServiceCredentialScanPropertiesCredentialOutput;
  shareName?: string;
}

export interface AzureFileServiceCredentialScanPropertiesCredentialOutput
  extends CredentialReferenceOutput {}

export interface AzureFileServiceCredentialScanOutput extends ScanOutputBase {
  properties?: AzureFileServiceCredentialScanPropertiesAutoGeneratedOutput;
  kind: "AzureFileServiceCredential";
}

export interface AzureFileServiceCredentialScanPropertiesAutoGeneratedOutput
  extends AzureFileServiceCredentialScanPropertiesOutput {}

export interface AzureSqlScanPropertiesOutput extends ScanPropertiesOutput {
  serverEndpoint?: string;
  databaseName?: string;
}

export interface AzureSqlCredentialScanPropertiesOutput
  extends AzureSqlScanPropertiesOutput {
  credential?: AzureSqlCredentialScanPropertiesCredentialOutput;
}

export interface AzureSqlCredentialScanPropertiesCredentialOutput
  extends CredentialReferenceOutput {}

export interface AzureSqlDatabaseCredentialScanPropertiesOutput
  extends AzureSqlCredentialScanPropertiesOutput {}

export interface AzureSqlDatabaseCredentialScanOutput extends ScanOutputBase {
  properties?: AzureSqlDatabaseCredentialScanPropertiesAutoGeneratedOutput;
  kind: "AzureSqlDatabaseCredential";
}

export interface AzureSqlDatabaseCredentialScanPropertiesAutoGeneratedOutput
  extends AzureSqlDatabaseCredentialScanPropertiesOutput {}

export interface AzureSqlDatabaseMsiScanPropertiesOutput
  extends AzureSqlScanPropertiesOutput {}

export interface AzureSqlDatabaseMsiScanOutput extends ScanOutputBase {
  properties?: AzureSqlDatabaseMsiScanPropertiesAutoGeneratedOutput;
  kind: "AzureSqlDatabaseMsi";
}

export interface AzureSqlDatabaseMsiScanPropertiesAutoGeneratedOutput
  extends AzureSqlDatabaseMsiScanPropertiesOutput {}

export interface AmazonPostgreSqlCredentialScanPropertiesOutput
  extends ScanPropertiesOutput {
  credential?: AmazonPostgreSqlCredentialScanPropertiesCredentialOutput;
  serverEndpoint?: string;
  databaseName?: string;
  port?: string;
}

export interface AmazonPostgreSqlCredentialScanPropertiesCredentialOutput
  extends CredentialReferenceOutput {}

export interface AmazonPostgreSqlCredentialScanOutput extends ScanOutputBase {
  properties?: AmazonPostgreSqlCredentialScanPropertiesAutoGeneratedOutput;
  kind: "AmazonPostgreSqlCredential";
}

export interface AmazonPostgreSqlCredentialScanPropertiesAutoGeneratedOutput
  extends AmazonPostgreSqlCredentialScanPropertiesOutput {}

export interface AzurePostgreSqlCredentialScanPropertiesOutput
  extends ScanPropertiesOutput {
  credential?: AzurePostgreSqlCredentialScanPropertiesCredentialOutput;
  serverEndpoint?: string;
  databaseName?: string;
  port?: number;
  sslMode?: number;
}

export interface AzurePostgreSqlCredentialScanPropertiesCredentialOutput
  extends CredentialReferenceOutput {}

export interface AzurePostgreSqlCredentialScanOutput extends ScanOutputBase {
  properties?: AzurePostgreSqlCredentialScanPropertiesAutoGeneratedOutput;
  kind: "AzurePostgreSqlCredential";
}

export interface AzurePostgreSqlCredentialScanPropertiesAutoGeneratedOutput
  extends AzurePostgreSqlCredentialScanPropertiesOutput {}

export interface SqlServerDatabaseCredentialScanPropertiesOutput
  extends AzureSqlCredentialScanPropertiesOutput {}

export interface SqlServerDatabaseCredentialScanOutput extends ScanOutputBase {
  properties?: SqlServerDatabaseCredentialScanPropertiesAutoGeneratedOutput;
  kind: "SqlServerDatabaseCredential";
}

export interface SqlServerDatabaseCredentialScanPropertiesAutoGeneratedOutput
  extends SqlServerDatabaseCredentialScanPropertiesOutput {}

export interface AzureSqlDatabaseManagedInstanceCredentialScanPropertiesOutput
  extends AzureSqlCredentialScanPropertiesOutput {}

export interface AzureSqlDatabaseManagedInstanceCredentialScanOutput
  extends ScanOutputBase {
  properties?: AzureSqlDatabaseManagedInstanceCredentialScanPropertiesAutoGeneratedOutput;
  kind: "AzureSqlDatabaseManagedInstanceCredential";
}

export interface AzureSqlDatabaseManagedInstanceCredentialScanPropertiesAutoGeneratedOutput
  extends AzureSqlDatabaseManagedInstanceCredentialScanPropertiesOutput {}

export interface AzureSqlDatabaseManagedInstanceMsiScanPropertiesOutput
  extends AzureSqlScanPropertiesOutput {}

export interface AzureSqlDatabaseManagedInstanceMsiScanOutput
  extends ScanOutputBase {
  properties?: AzureSqlDatabaseManagedInstanceMsiScanPropertiesAutoGeneratedOutput;
  kind: "AzureSqlDatabaseManagedInstanceMsi";
}

export interface AzureSqlDatabaseManagedInstanceMsiScanPropertiesAutoGeneratedOutput
  extends AzureSqlDatabaseManagedInstanceMsiScanPropertiesOutput {}

export interface AzureSqlDataWarehouseCredentialScanPropertiesOutput
  extends AzureSqlCredentialScanPropertiesOutput {}

export interface AzureSqlDataWarehouseCredentialScanOutput
  extends ScanOutputBase {
  properties?: AzureSqlDataWarehouseCredentialScanPropertiesAutoGeneratedOutput;
  kind: "AzureSqlDataWarehouseCredential";
}

export interface AzureSqlDataWarehouseCredentialScanPropertiesAutoGeneratedOutput
  extends AzureSqlDataWarehouseCredentialScanPropertiesOutput {}

export interface AzureSqlDataWarehouseMsiScanPropertiesOutput
  extends AzureSqlScanPropertiesOutput {}

export interface AzureSqlDataWarehouseMsiScanOutput extends ScanOutputBase {
  properties?: AzureSqlDataWarehouseMsiScanPropertiesAutoGeneratedOutput;
  kind: "AzureSqlDataWarehouseMsi";
}

export interface AzureSqlDataWarehouseMsiScanPropertiesAutoGeneratedOutput
  extends AzureSqlDataWarehouseMsiScanPropertiesOutput {}

export interface AzureMySqlScanPropertiesOutput extends ScanPropertiesOutput {
  serverEndpoint?: string;
  port?: number;
  databaseName?: string;
  credential?: AzureMySqlScanPropertiesCredentialOutput;
}

export interface AzureMySqlScanPropertiesCredentialOutput
  extends CredentialReferenceOutput {}

export interface AzureMySqlCredentialScanPropertiesOutput
  extends AzureMySqlScanPropertiesOutput {}

export interface AzureMySqlCredentialScanOutput extends ScanOutputBase {
  properties?: AzureMySqlCredentialScanPropertiesAutoGeneratedOutput;
  kind: "AzureMySqlCredential";
}

export interface AzureMySqlCredentialScanPropertiesAutoGeneratedOutput
  extends AzureMySqlCredentialScanPropertiesOutput {}

export interface MitiScanPropertiesOutput extends ScanPropertiesOutput {
  maximumMemoryAllowedInGb?: string;
  mitiCache?: string;
}

export interface AzureStorageCredentialScanPropertiesOutput
  extends ScanPropertiesOutput {
  credential?: AzureStorageCredentialScanPropertiesCredentialOutput;
}

export interface AzureStorageCredentialScanPropertiesCredentialOutput
  extends CredentialReferenceOutput {}

export interface AzureStorageCredentialScanOutput extends ScanOutputBase {
  properties?: AzureStorageCredentialScanPropertiesAutoGeneratedOutput;
  kind: "AzureStorageCredential";
}

export interface AzureStorageCredentialScanPropertiesAutoGeneratedOutput
  extends AzureStorageCredentialScanPropertiesOutput {}

export interface AzureStorageMsiScanPropertiesOutput
  extends ScanPropertiesOutput {}

export interface AzureStorageMsiScanOutput extends ScanOutputBase {
  properties?: AzureStorageMsiScanPropertiesAutoGeneratedOutput;
  kind: "AzureStorageMsi";
}

export interface AzureStorageMsiScanPropertiesAutoGeneratedOutput
  extends AzureStorageMsiScanPropertiesOutput {}

export interface TeradataCredentialScanPropertiesOutput
  extends MitiScanPropertiesOutput {
  credential?: TeradataCredentialScanPropertiesCredentialOutput;
  schema?: string;
  driverLocation?: string;
}

export interface TeradataCredentialScanPropertiesCredentialOutput
  extends CredentialReferenceOutput {}

export interface TeradataCredentialScanOutput extends ScanOutputBase {
  properties?: TeradataTeradataCredentialScanPropertiesOutput;
  kind: "TeradataTeradataCredential";
}

export interface TeradataTeradataCredentialScanPropertiesOutput
  extends TeradataCredentialScanPropertiesOutput {}

export interface TeradataUserPassScanPropertiesOutput
  extends ScanPropertiesOutput {
  username?: string;
  password?: string;
}

export interface TeradataUserPassScanOutput extends ScanOutputBase {
  properties?: TeradataUserPassScanPropertiesAutoGeneratedOutput;
  kind: "TeradataUserPass";
}

export interface TeradataUserPassScanPropertiesAutoGeneratedOutput
  extends TeradataUserPassScanPropertiesOutput {}

export interface TeradataTeradataUserPassScanPropertiesOutput
  extends MitiScanPropertiesOutput {
  username?: string;
  password?: string;
  schema?: string;
  driverLocation?: string;
}

export interface TeradataTeradataUserPassScanOutput extends ScanOutputBase {
  properties?: TeradataTeradataUserPassScanPropertiesAutoGeneratedOutput;
  kind: "TeradataTeradataUserPass";
}

export interface TeradataTeradataUserPassScanPropertiesAutoGeneratedOutput
  extends TeradataTeradataUserPassScanPropertiesOutput {}

export interface OracleCredentialScanPropertiesOutput
  extends MitiScanPropertiesOutput {
  credential?: OracleCredentialScanPropertiesCredentialOutput;
  schema?: string;
  driverLocation?: string;
}

export interface OracleCredentialScanPropertiesCredentialOutput
  extends CredentialReferenceOutput {}

export interface OracleCredentialScanOutput extends ScanOutputBase {
  properties?: OracleOracleCredentialScanPropertiesOutput;
  kind: "OracleOracleCredential";
}

export interface OracleOracleCredentialScanPropertiesOutput
  extends OracleCredentialScanPropertiesOutput {}

export interface OracleUserPassScanPropertiesOutput
  extends MitiScanPropertiesOutput {
  username?: string;
  password?: string;
  schema?: string;
  driverLocation?: string;
}

export interface OracleUserPassScanOutput extends ScanOutputBase {
  properties?: OracleOracleUserPassScanPropertiesOutput;
  kind: "OracleOracleUserPass";
}

export interface OracleOracleUserPassScanPropertiesOutput
  extends OracleUserPassScanPropertiesOutput {}

export interface SapS4HanaSapS4HanaCredentialScanPropertiesOutput
  extends MitiScanPropertiesOutput {
  clientId?: string;
  credential?: SapS4HanaSapS4HanaCredentialScanPropertiesCredentialOutput;
  jCoLibraryPath?: string;
}

export interface SapS4HanaSapS4HanaCredentialScanPropertiesCredentialOutput
  extends CredentialReferenceOutput {}

export interface SapS4HanaSapS4HanaCredentialScanOutput extends ScanOutputBase {
  properties?: SapS4HanaSapS4HanaCredentialScanPropertiesAutoGeneratedOutput;
  kind: "SapS4HanaSapS4HanaCredential";
}

export interface SapS4HanaSapS4HanaCredentialScanPropertiesAutoGeneratedOutput
  extends SapS4HanaSapS4HanaCredentialScanPropertiesOutput {}

export interface SapS4HanaSapS4HanaUserPassScanPropertiesOutput
  extends MitiScanPropertiesOutput {
  clientId?: string;
  username?: string;
  password?: string;
  jCoLibraryPath?: string;
}

export interface SapS4HanaSapS4HanaUserPassScanOutput extends ScanOutputBase {
  properties?: SapS4HanaSapS4HanaUserPassScanPropertiesAutoGeneratedOutput;
  kind: "SapS4HanaSapS4HanaUserPass";
}

export interface SapS4HanaSapS4HanaUserPassScanPropertiesAutoGeneratedOutput
  extends SapS4HanaSapS4HanaUserPassScanPropertiesOutput {}

export interface SapEccCredentialScanPropertiesOutput
  extends MitiScanPropertiesOutput {
  clientId?: string;
  credential?: SapEccCredentialScanPropertiesCredentialOutput;
  jCoLibraryPath?: string;
}

export interface SapEccCredentialScanPropertiesCredentialOutput
  extends CredentialReferenceOutput {}

export interface SapEccCredentialScanOutput extends ScanOutputBase {
  properties?: SapEccSapEccCredentialScanPropertiesOutput;
  kind: "SapEccSapEccCredential";
}

export interface SapEccSapEccCredentialScanPropertiesOutput
  extends SapEccCredentialScanPropertiesOutput {}

export interface SapEccUserPassScanPropertiesOutput
  extends MitiScanPropertiesOutput {
  clientId?: string;
  username?: string;
  password?: string;
  jCoLibraryPath?: string;
}

export interface SapEccUserPassScanOutput extends ScanOutputBase {
  properties?: SapEccSapEccUserPassScanPropertiesOutput;
  kind: "SapEccSapEccUserPass";
}

export interface SapEccSapEccUserPassScanPropertiesOutput
  extends SapEccUserPassScanPropertiesOutput {}

export interface PowerBIDelegatedScanPropertiesOutput
  extends ScanPropertiesOutput {
  tenant?: string;
  authenticationType?: string;
  clientId?: string;
  userName?: string;
  password?: string;
  includePersonalWorkspaces?: boolean;
}

export interface PowerBIDelegatedScanOutput extends ScanOutputBase {
  properties?: PowerBIDelegatedScanPropertiesAutoGeneratedOutput;
  kind: "PowerBIDelegated";
}

export interface PowerBIDelegatedScanPropertiesAutoGeneratedOutput
  extends PowerBIDelegatedScanPropertiesOutput {}

export interface PowerBIMsiScanPropertiesOutput extends ScanPropertiesOutput {
  includePersonalWorkspaces?: boolean;
}

export interface PowerBIMsiScanOutput extends ScanOutputBase {
  properties?: PowerBIMsiScanPropertiesAutoGeneratedOutput;
  kind: "PowerBIMsi";
}

export interface PowerBIMsiScanPropertiesAutoGeneratedOutput
  extends PowerBIMsiScanPropertiesOutput {}

export interface AzureSubscriptionSystemScanRulesetOutput
  extends SystemScanRulesetOutputBase {
  properties?: AzureSubscriptionSystemScanRulesetPropertiesOutput;
  kind: "None";
}

export interface AzureSubscriptionSystemScanRulesetPropertiesOutput
  extends AzureSubscriptionScanRulesetPropertiesOutput {}

export interface AzureResourceGroupSystemScanRulesetOutput
  extends SystemScanRulesetOutputBase {
  properties?: AzureResourceGroupSystemScanRulesetPropertiesOutput;
  kind: "None";
}

export interface AzureResourceGroupSystemScanRulesetPropertiesOutput
  extends AzureResourceGroupScanRulesetPropertiesOutput {}

export interface AzureSynapseWorkspaceSystemScanRulesetOutput
  extends SystemScanRulesetOutputBase {
  properties?: AzureSynapseWorkspaceSystemScanRulesetPropertiesOutput;
  kind: "None";
}

export interface AzureSynapseWorkspaceSystemScanRulesetPropertiesOutput
  extends AzureSynapseWorkspaceScanRulesetPropertiesOutput {}

export interface AzureSynapseSystemScanRulesetOutput
  extends SystemScanRulesetOutputBase {
  properties?: AzureSynapseSystemScanRulesetPropertiesOutput;
  kind: "None";
}

export interface AzureSynapseSystemScanRulesetPropertiesOutput
  extends AzureSynapseScanRulesetPropertiesOutput {}

export interface AdlsGen1SystemScanRulesetOutput
  extends SystemScanRulesetOutputBase {
  properties?: AdlsGen1SystemScanRulesetPropertiesOutput;
  kind: "None";
}

export interface AdlsGen1SystemScanRulesetPropertiesOutput
  extends AdlsGen1ScanRulesetPropertiesOutput {}

export interface AdlsGen2SystemScanRulesetOutput
  extends SystemScanRulesetOutputBase {
  properties?: AdlsGen2SystemScanRulesetPropertiesOutput;
  kind: "None";
}

export interface AdlsGen2SystemScanRulesetPropertiesOutput
  extends AdlsGen2ScanRulesetPropertiesOutput {}

export interface AmazonAccountSystemScanRulesetOutput
  extends SystemScanRulesetOutputBase {
  properties?: AmazonAccountSystemScanRulesetPropertiesOutput;
  kind: "None";
}

export interface AmazonAccountSystemScanRulesetPropertiesOutput
  extends AmazonAccountScanRulesetPropertiesOutput {}

export interface AmazonS3SystemScanRulesetOutput
  extends SystemScanRulesetOutputBase {
  properties?: AmazonS3SystemScanRulesetPropertiesOutput;
  kind: "None";
}

export interface AmazonS3SystemScanRulesetPropertiesOutput
  extends AmazonS3ScanRulesetPropertiesOutput {}

export interface AmazonSqlSystemScanRulesetOutput
  extends SystemScanRulesetOutputBase {
  properties?: AmazonSqlSystemScanRulesetPropertiesOutput;
  kind: "None";
}

export interface AmazonSqlSystemScanRulesetPropertiesOutput
  extends AmazonSqlScanRulesetPropertiesOutput {}

export interface AzureCosmosDbSystemScanRulesetOutput
  extends SystemScanRulesetOutputBase {
  properties?: AzureCosmosDbSystemScanRulesetPropertiesOutput;
  kind: "None";
}

export interface AzureCosmosDbSystemScanRulesetPropertiesOutput
  extends AzureCosmosDbScanRulesetPropertiesOutput {}

export interface AzureDataExplorerSystemScanRulesetOutput
  extends SystemScanRulesetOutputBase {
  properties?: AzureDataExplorerSystemScanRulesetPropertiesOutput;
  kind: "None";
}

export interface AzureDataExplorerSystemScanRulesetPropertiesOutput
  extends AzureDataExplorerScanRulesetPropertiesOutput {}

export interface AzureFileServiceSystemScanRulesetOutput
  extends SystemScanRulesetOutputBase {
  properties?: AzureFileServiceSystemScanRulesetPropertiesOutput;
  kind: "None";
}

export interface AzureFileServiceSystemScanRulesetPropertiesOutput
  extends AzureFileServiceScanRulesetPropertiesOutput {}

export interface AzureSqlDatabaseSystemScanRulesetOutput
  extends SystemScanRulesetOutputBase {
  properties?: AzureSqlDatabaseSystemScanRulesetPropertiesOutput;
  kind: "None";
}

export interface AzureSqlDatabaseSystemScanRulesetPropertiesOutput
  extends AzureSqlDatabaseScanRulesetPropertiesOutput {}

export interface AmazonPostgreSqlSystemScanRulesetOutput
  extends SystemScanRulesetOutputBase {
  properties?: AmazonPostgreSqlSystemScanRulesetPropertiesOutput;
  kind: "None";
}

export interface AmazonPostgreSqlSystemScanRulesetPropertiesOutput
  extends AmazonPostgreSqlScanRulesetPropertiesOutput {}

export interface AzurePostgreSqlSystemScanRulesetOutput
  extends SystemScanRulesetOutputBase {
  properties?: AzurePostgreSqlSystemScanRulesetPropertiesOutput;
  kind: "None";
}

export interface AzurePostgreSqlSystemScanRulesetPropertiesOutput
  extends AzurePostgreSqlScanRulesetPropertiesOutput {}

export interface SqlServerDatabaseSystemScanRulesetOutput
  extends SystemScanRulesetOutputBase {
  properties?: SqlServerDatabaseSystemScanRulesetPropertiesOutput;
  kind: "None";
}

export interface SqlServerDatabaseSystemScanRulesetPropertiesOutput
  extends SqlServerDatabaseScanRulesetPropertiesOutput {}

export interface AzureSqlDatabaseManagedInstanceSystemScanRulesetOutput
  extends SystemScanRulesetOutputBase {
  properties?: AzureSqlDatabaseManagedInstanceSystemScanRulesetPropertiesOutput;
  kind: "None";
}

export interface AzureSqlDatabaseManagedInstanceSystemScanRulesetPropertiesOutput
  extends AzureSqlDatabaseManagedInstanceScanRulesetPropertiesOutput {}

export interface AzureSqlDataWarehouseSystemScanRulesetOutput
  extends SystemScanRulesetOutputBase {
  properties?: AzureSqlDataWarehouseSystemScanRulesetPropertiesOutput;
  kind: "None";
}

export interface AzureSqlDataWarehouseSystemScanRulesetPropertiesOutput
  extends AzureSqlDataWarehouseScanRulesetPropertiesOutput {}

export interface AzureMySqlSystemScanRulesetOutput
  extends SystemScanRulesetOutputBase {
  properties?: AzureMySqlSystemScanRulesetPropertiesOutput;
  kind: "None";
}

export interface AzureMySqlSystemScanRulesetPropertiesOutput
  extends AzureMySqlScanRulesetPropertiesOutput {}

export interface AzureStorageSystemScanRulesetOutput
  extends SystemScanRulesetOutputBase {
  properties?: AzureStorageSystemScanRulesetPropertiesOutput;
  kind: "None";
}

export interface AzureStorageSystemScanRulesetPropertiesOutput
  extends AzureStorageScanRulesetPropertiesOutput {}

export interface TeradataSystemScanRulesetOutput
  extends SystemScanRulesetOutputBase {
  properties?: TeradataSystemScanRulesetPropertiesOutput;
  kind: "None";
}

export interface TeradataSystemScanRulesetPropertiesOutput
  extends TeradataScanRulesetPropertiesOutput {}

export interface OracleSystemScanRulesetOutput
  extends SystemScanRulesetOutputBase {
  properties?: OracleSystemScanRulesetPropertiesOutput;
  kind: "None";
}

export interface OracleSystemScanRulesetPropertiesOutput
  extends OracleScanRulesetPropertiesOutput {}

export interface SapS4HanaSystemScanRulesetOutput
  extends SystemScanRulesetOutputBase {
  properties?: SapS4HanaSystemScanRulesetPropertiesOutput;
  kind: "None";
}

export interface SapS4HanaSystemScanRulesetPropertiesOutput
  extends SapS4HanaScanRulesetPropertiesOutput {}

export interface SapEccSystemScanRulesetOutput
  extends SystemScanRulesetOutputBase {
  properties?: SapEccSystemScanRulesetPropertiesOutput;
  kind: "None";
}

export interface SapEccSystemScanRulesetPropertiesOutput
  extends SapEccScanRulesetPropertiesOutput {}

export interface PowerBISystemScanRulesetOutput
  extends SystemScanRulesetOutputBase {
  properties?: PowerBISystemScanRulesetPropertiesOutput;
  kind: "None";
}

export interface PowerBISystemScanRulesetPropertiesOutput
  extends PowerBIScanRulesetPropertiesOutput {}

export type ClassificationRuleOutput =
  | ClassificationRuleOutputBase
  | SystemClassificationRuleOutput
  | CustomClassificationRuleOutput;
export type DataSourceOutput =
  | DataSourceOutputBase
  | AzureSubscriptionDataSourceOutput
  | AzureResourceGroupDataSourceOutput
  | AzureSynapseWorkspaceDataSourceOutput
  | AzureSynapseDataSourceOutput
  | AdlsGen1DataSourceOutput
  | AdlsGen2DataSourceOutput
  | AmazonAccountDataSourceOutput
  | AmazonS3DataSourceOutput
  | AmazonSqlDataSourceOutput
  | AzureCosmosDbDataSourceOutput
  | AzureDataExplorerDataSourceOutput
  | AzureFileServiceDataSourceOutput
  | AzureSqlDatabaseDataSourceOutput
  | AmazonPostgreSqlDataSourceOutput
  | AzurePostgreSqlDataSourceOutput
  | SqlServerDatabaseDataSourceOutput
  | AzureSqlDatabaseManagedInstanceDataSourceOutput
  | AzureSqlDataWarehouseDataSourceOutput
  | AzureMySqlDataSourceOutput
  | AzureStorageDataSourceOutput
  | TeradataDataSourceOutput
  | OracleDataSourceOutput
  | SapS4HanaDataSourceOutput
  | SapEccDataSourceOutput
  | PowerBIDataSourceOutput;
export type ScanOutput =
  | ScanOutputBase
  | AzureSubscriptionCredentialScanOutput
  | AzureSubscriptionMsiScanOutput
  | AzureResourceGroupCredentialScanOutput
  | AzureResourceGroupMsiScanOutput
  | AzureSynapseWorkspaceCredentialScanOutput
  | AzureSynapseWorkspaceMsiScanOutput
  | AzureSynapseCredentialScanOutput
  | AzureSynapseMsiScanOutput
  | AdlsGen1CredentialScanOutput
  | AdlsGen1MsiScanOutput
  | AdlsGen2CredentialScanOutput
  | AdlsGen2MsiScanOutput
  | AmazonAccountCredentialScanOutput
  | AmazonS3CredentialScanOutput
  | AmazonS3RoleARNScanOutput
  | AmazonSqlCredentialScanOutput
  | AzureCosmosDbCredentialScanOutput
  | AzureDataExplorerCredentialScanOutput
  | AzureDataExplorerMsiScanOutput
  | AzureFileServiceCredentialScanOutput
  | AzureSqlDatabaseCredentialScanOutput
  | AzureSqlDatabaseMsiScanOutput
  | AmazonPostgreSqlCredentialScanOutput
  | AzurePostgreSqlCredentialScanOutput
  | SqlServerDatabaseCredentialScanOutput
  | AzureSqlDatabaseManagedInstanceCredentialScanOutput
  | AzureSqlDatabaseManagedInstanceMsiScanOutput
  | AzureSqlDataWarehouseCredentialScanOutput
  | AzureSqlDataWarehouseMsiScanOutput
  | AzureMySqlCredentialScanOutput
  | AzureStorageCredentialScanOutput
  | AzureStorageMsiScanOutput
  | TeradataCredentialScanOutput
  | TeradataUserPassScanOutput
  | TeradataTeradataUserPassScanOutput
  | OracleCredentialScanOutput
  | OracleUserPassScanOutput
  | SapS4HanaSapS4HanaCredentialScanOutput
  | SapS4HanaSapS4HanaUserPassScanOutput
  | SapEccCredentialScanOutput
  | SapEccUserPassScanOutput
  | PowerBIDelegatedScanOutput
  | PowerBIMsiScanOutput;
export type ScanRulesetOutput =
  | ScanRulesetOutputBase
  | AzureSubscriptionScanRulesetOutput
  | AzureResourceGroupScanRulesetOutput
  | AzureSynapseWorkspaceScanRulesetOutput
  | AzureSynapseScanRulesetOutput
  | AdlsGen1ScanRulesetOutput
  | AdlsGen2ScanRulesetOutput
  | AmazonAccountScanRulesetOutput
  | AmazonS3ScanRulesetOutput
  | AmazonSqlScanRulesetOutput
  | AzureCosmosDbScanRulesetOutput
  | AzureDataExplorerScanRulesetOutput
  | AzureFileServiceScanRulesetOutput
  | AzureSqlDatabaseScanRulesetOutput
  | AmazonPostgreSqlScanRulesetOutput
  | AzurePostgreSqlScanRulesetOutput
  | SqlServerDatabaseScanRulesetOutput
  | AzureSqlDatabaseManagedInstanceScanRulesetOutput
  | AzureSqlDataWarehouseScanRulesetOutput
  | AzureMySqlScanRulesetOutput
  | AzureStorageScanRulesetOutput
  | TeradataScanRulesetOutput
  | OracleScanRulesetOutput
  | SapS4HanaScanRulesetOutput
  | SapEccScanRulesetOutput
  | PowerBIScanRulesetOutput;
export type SystemScanRulesetOutput =
  | SystemScanRulesetOutputBase
  | AzureSubscriptionSystemScanRulesetOutput
  | AzureResourceGroupSystemScanRulesetOutput
  | AzureSynapseWorkspaceSystemScanRulesetOutput
  | AzureSynapseSystemScanRulesetOutput
  | AdlsGen1SystemScanRulesetOutput
  | AdlsGen2SystemScanRulesetOutput
  | AmazonAccountSystemScanRulesetOutput
  | AmazonS3SystemScanRulesetOutput
  | AmazonSqlSystemScanRulesetOutput
  | AzureCosmosDbSystemScanRulesetOutput
  | AzureDataExplorerSystemScanRulesetOutput
  | AzureFileServiceSystemScanRulesetOutput
  | AzureSqlDatabaseSystemScanRulesetOutput
  | AmazonPostgreSqlSystemScanRulesetOutput
  | AzurePostgreSqlSystemScanRulesetOutput
  | SqlServerDatabaseSystemScanRulesetOutput
  | AzureSqlDatabaseManagedInstanceSystemScanRulesetOutput
  | AzureSqlDataWarehouseSystemScanRulesetOutput
  | AzureMySqlSystemScanRulesetOutput
  | AzureStorageSystemScanRulesetOutput
  | TeradataSystemScanRulesetOutput
  | OracleSystemScanRulesetOutput
  | SapS4HanaSystemScanRulesetOutput
  | SapEccSystemScanRulesetOutput
  | PowerBISystemScanRulesetOutput;
export type ClassificationRulePatternOutput = RegexClassificationRulePatternOutput;
