/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { PagedAsyncIterableIterator } from "@azure/core-paging";
import {
  UpdateSummaries,
  UpdateSummariesListOptionalParams,
  UpdateSummariesGetOptionalParams,
  UpdateSummariesGetResponse
} from "../models";

/// <reference lib="esnext.asynciterable" />
/** Interface representing a UpdateSummariesOperations. */
export interface UpdateSummariesOperations {
  /**
   * List all Update summaries under the HCI cluster
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param clusterName The name of the cluster.
   * @param options The options parameters.
   */
  list(
    resourceGroupName: string,
    clusterName: string,
    options?: UpdateSummariesListOptionalParams
  ): PagedAsyncIterableIterator<UpdateSummaries>;
  /**
   * Get all Update summaries under the HCI cluster
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param clusterName The name of the cluster.
   * @param options The options parameters.
   */
  get(
    resourceGroupName: string,
    clusterName: string,
    options?: UpdateSummariesGetOptionalParams
  ): Promise<UpdateSummariesGetResponse>;
}
