/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "../models";
import * as Mappers from "../models/getOperationStatusMappers";
import * as Parameters from "../models/parameters";
import { SubscriptionClientContext } from "../subscriptionClientContext";

/** Class representing a GetOperationStatus. */
export class GetOperationStatus {
  private readonly client: SubscriptionClientContext;

  /**
   * Create a GetOperationStatus.
   * @param {SubscriptionClientContext} client Reference to the service client.
   */
  constructor(client: SubscriptionClientContext) {
    this.client = client;
  }

  /**
   * The operation to find out the purchase Operation status
   * @param subscriptionId Subscription Id.
   * @param id Id.
   * @param [options] The optional parameters
   * @returns Promise<Models.GetOperationStatusGetResponse>
   */
  get(subscriptionId: string, id: string, options?: msRest.RequestOptionsBase): Promise<Models.GetOperationStatusGetResponse>;
  /**
   * @param subscriptionId Subscription Id.
   * @param id Id.
   * @param callback The callback
   */
  get(subscriptionId: string, id: string, callback: msRest.ServiceCallback<Models.OperationStatusResponseResult>): void;
  /**
   * @param subscriptionId Subscription Id.
   * @param id Id.
   * @param options The optional parameters
   * @param callback The callback
   */
  get(subscriptionId: string, id: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.OperationStatusResponseResult>): void;
  get(subscriptionId: string, id: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.OperationStatusResponseResult>, callback?: msRest.ServiceCallback<Models.OperationStatusResponseResult>): Promise<Models.GetOperationStatusGetResponse> {
    return this.client.sendOperationRequest(
      {
        subscriptionId,
        id,
        options
      },
      getOperationSpec,
      callback) as Promise<Models.GetOperationStatusGetResponse>;
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const getOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "subscriptions/{subscriptionId}/providers/Microsoft.Subscription/OperationStatus/{Id}",
  urlParameters: [
    Parameters.subscriptionId,
    Parameters.id
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {
      bodyMapper: Mappers.OperationStatusResponseResult,
      headersMapper: Mappers.GetOperationStatusGetHeaders
    },
    202: {
      headersMapper: Mappers.GetOperationStatusGetHeaders
    },
    default: {
      bodyMapper: Mappers.ErrorResponse
    }
  },
  serializer
};
