/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { PagedAsyncIterableIterator } from "@azure/core-paging";
import { PollerLike, PollOperationState } from "@azure/core-lro";
import {
  LabelingJob,
  LabelingJobsListOptionalParams,
  LabelingJobsDeleteOptionalParams,
  LabelingJobsGetOptionalParams,
  LabelingJobsGetResponse,
  LabelingJobsCreateOrUpdateOptionalParams,
  LabelingJobsCreateOrUpdateResponse,
  ExportSummaryUnion,
  LabelingJobsExportLabelsOptionalParams,
  LabelingJobsExportLabelsResponse,
  LabelingJobsPauseOptionalParams,
  LabelingJobsResumeOptionalParams
} from "../models";

/// <reference lib="esnext.asynciterable" />
/** Interface representing a LabelingJobs. */
export interface LabelingJobs {
  /**
   * Lists labeling jobs in the workspace.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param workspaceName Name of Azure Machine Learning workspace.
   * @param options The options parameters.
   */
  list(
    resourceGroupName: string,
    workspaceName: string,
    options?: LabelingJobsListOptionalParams
  ): PagedAsyncIterableIterator<LabelingJob>;
  /**
   * Delete a labeling job.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param workspaceName Name of Azure Machine Learning workspace.
   * @param id The name and identifier for the LabelingJob.
   * @param options The options parameters.
   */
  delete(
    resourceGroupName: string,
    workspaceName: string,
    id: string,
    options?: LabelingJobsDeleteOptionalParams
  ): Promise<void>;
  /**
   * Gets a labeling job by name/id.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param workspaceName Name of Azure Machine Learning workspace.
   * @param id The name and identifier for the LabelingJob.
   * @param options The options parameters.
   */
  get(
    resourceGroupName: string,
    workspaceName: string,
    id: string,
    options?: LabelingJobsGetOptionalParams
  ): Promise<LabelingJobsGetResponse>;
  /**
   * Creates or updates a labeling job (asynchronous).
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param workspaceName Name of Azure Machine Learning workspace.
   * @param id The name and identifier for the LabelingJob.
   * @param body LabelingJob definition object.
   * @param options The options parameters.
   */
  beginCreateOrUpdate(
    resourceGroupName: string,
    workspaceName: string,
    id: string,
    body: LabelingJob,
    options?: LabelingJobsCreateOrUpdateOptionalParams
  ): Promise<
    PollerLike<
      PollOperationState<LabelingJobsCreateOrUpdateResponse>,
      LabelingJobsCreateOrUpdateResponse
    >
  >;
  /**
   * Creates or updates a labeling job (asynchronous).
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param workspaceName Name of Azure Machine Learning workspace.
   * @param id The name and identifier for the LabelingJob.
   * @param body LabelingJob definition object.
   * @param options The options parameters.
   */
  beginCreateOrUpdateAndWait(
    resourceGroupName: string,
    workspaceName: string,
    id: string,
    body: LabelingJob,
    options?: LabelingJobsCreateOrUpdateOptionalParams
  ): Promise<LabelingJobsCreateOrUpdateResponse>;
  /**
   * Export labels from a labeling job (asynchronous).
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param workspaceName Name of Azure Machine Learning workspace.
   * @param id The name and identifier for the LabelingJob.
   * @param body The export summary.
   * @param options The options parameters.
   */
  beginExportLabels(
    resourceGroupName: string,
    workspaceName: string,
    id: string,
    body: ExportSummaryUnion,
    options?: LabelingJobsExportLabelsOptionalParams
  ): Promise<
    PollerLike<
      PollOperationState<LabelingJobsExportLabelsResponse>,
      LabelingJobsExportLabelsResponse
    >
  >;
  /**
   * Export labels from a labeling job (asynchronous).
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param workspaceName Name of Azure Machine Learning workspace.
   * @param id The name and identifier for the LabelingJob.
   * @param body The export summary.
   * @param options The options parameters.
   */
  beginExportLabelsAndWait(
    resourceGroupName: string,
    workspaceName: string,
    id: string,
    body: ExportSummaryUnion,
    options?: LabelingJobsExportLabelsOptionalParams
  ): Promise<LabelingJobsExportLabelsResponse>;
  /**
   * Pause a labeling job.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param workspaceName Name of Azure Machine Learning workspace.
   * @param id The name and identifier for the LabelingJob.
   * @param options The options parameters.
   */
  pause(
    resourceGroupName: string,
    workspaceName: string,
    id: string,
    options?: LabelingJobsPauseOptionalParams
  ): Promise<void>;
  /**
   * Resume a labeling job (asynchronous).
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param workspaceName Name of Azure Machine Learning workspace.
   * @param id The name and identifier for the LabelingJob.
   * @param options The options parameters.
   */
  beginResume(
    resourceGroupName: string,
    workspaceName: string,
    id: string,
    options?: LabelingJobsResumeOptionalParams
  ): Promise<PollerLike<PollOperationState<void>, void>>;
  /**
   * Resume a labeling job (asynchronous).
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param workspaceName Name of Azure Machine Learning workspace.
   * @param id The name and identifier for the LabelingJob.
   * @param options The options parameters.
   */
  beginResumeAndWait(
    resourceGroupName: string,
    workspaceName: string,
    id: string,
    options?: LabelingJobsResumeOptionalParams
  ): Promise<void>;
}
