/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

export {
  Advisor,
  AutomaticTuningOptions,
  BaseResource,
  CloudError,
  DatabaseAutomaticTuning,
  DatabaseBlobAuditingPolicy,
  EncryptionProtector,
  FailoverGroup,
  FailoverGroupReadOnlyEndpoint,
  FailoverGroupReadWriteEndpoint,
  FirewallRule,
  ManagedInstance,
  PartnerInfo,
  ProxyResource,
  ProxyResourceWithWritableName,
  RecommendedAction,
  RecommendedActionErrorInfo,
  RecommendedActionImpactRecord,
  RecommendedActionImplementationInfo,
  RecommendedActionMetricInfo,
  RecommendedActionStateInfo,
  Resource,
  ResourceIdentity,
  ResourceWithWritableName,
  Server,
  ServerKey,
  ServerKeyListResult,
  Sku,
  SubscriptionUsage,
  SyncAgent,
  SyncAgentLinkedDatabase,
  SyncGroup,
  SyncGroupSchema,
  SyncGroupSchemaTable,
  SyncGroupSchemaTableColumn,
  SyncMember,
  TrackedResource,
  VirtualCluster,
  VirtualNetworkRule
} from "../models/mappers";
